import { ThemeConfig, LinkStyle } from "@/types/config";

export interface ColorPalette {
  id: string;
  name: string;
  category:
    | "Dark"
    | "Neon"
    | "Pastel"
    | "Minimal"
    | "Luxury"
    | "Nature"
    | "Vibrant"
    | "Light"
    | "Developer"
    | "Retro";
  description: string;
  previewColors: string[]; // 4 or 5 hex swatches
  accentColor: string;
  config: {
    theme: {
      background: {
        type: "linear-gradient" | "solid" | "radial-gradient" | "mesh";
        solidColor: string;
        gradientAngle?: number;
        gradientStops?: { color: string; position: number }[];
        meshColors?: string[];
        shapesColor: string;
      };
      headingColor: string;
      bioTextColor: string;
    };
    linkStyle: Partial<LinkStyle>;
  };
}

export const COLOR_PALETTES: ColorPalette[] = [
  // ──────────────────────────────────────────────────────────────────────────
  // 1. DEVELOPER & CODE EDITOR THEMES (Famous Coding Palettes)
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: "monokai-pro",
    name: "Monokai Pro",
    category: "Developer",
    description: "Beloved warm charcoal developer palette with neon yellow, magenta, and mint",
    previewColors: ["#221f22", "#ffd866", "#ff6188", "#a9dc76"],
    accentColor: "#ffd866",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#221f22",
          shapesColor: "#ffd866",
        },
        headingColor: "#fcfcfa",
        bioTextColor: "#ffd866",
      },
      linkStyle: {
        surfaceColor: "#2d2a2e",
        borderColor: "rgba(255, 216, 102, 0.3)",
        textColor: "#fcfcfa",
        subtextColor: "#a9dc76",
        iconColor: "#ff6188",
        glowColor: "#ffd866",
        glowEnabled: true,
        glowOpacity: 60,
      },
    },
  },
  {
    id: "one-dark-pro",
    name: "One Dark Pro (Atom)",
    category: "Developer",
    description: "Iconic Atom editor theme with balanced slate, cyan, coral, and soft purple",
    previewColors: ["#1e1e24", "#56b6c2", "#e06c75", "#c678dd"],
    accentColor: "#56b6c2",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#1e1e24",
          gradientAngle: 145,
          gradientStops: [
            { color: "#18181e", position: 0 },
            { color: "#21252b", position: 50 },
            { color: "#1a1d22", position: 100 },
          ],
          shapesColor: "#56b6c2",
        },
        headingColor: "#abb2bf",
        bioTextColor: "#56b6c2",
      },
      linkStyle: {
        surfaceColor: "#282c34",
        borderColor: "rgba(86, 182, 194, 0.3)",
        textColor: "#ffffff",
        subtextColor: "#c678dd",
        iconColor: "#e06c75",
        glowColor: "#56b6c2",
        glowEnabled: true,
        glowOpacity: 55,
      },
    },
  },
  {
    id: "github-dark-dimmed",
    name: "GitHub Dark Dimmed",
    category: "Developer",
    description: "Modern softened GitHub dark theme with soft blue, mint, and slate",
    previewColors: ["#1c2128", "#539bf5", "#76e3ea", "#22272e"],
    accentColor: "#539bf5",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#1c2128",
          shapesColor: "#539bf5",
        },
        headingColor: "#adbac7",
        bioTextColor: "#76e3ea",
      },
      linkStyle: {
        surfaceColor: "#22272e",
        borderColor: "rgba(83, 155, 245, 0.35)",
        textColor: "#adbac7",
        subtextColor: "#768390",
        iconColor: "#539bf5",
        glowColor: "#539bf5",
        glowEnabled: true,
        glowOpacity: 50,
      },
    },
  },
  {
    id: "gruvbox-dark",
    name: "Gruvbox Retro Groove",
    category: "Developer",
    description: "Warm retro groove palette with earthy autumn orange, aqua, and yellow",
    previewColors: ["#1d2021", "#fe8019", "#8ec07c", "#fabd2f"],
    accentColor: "#fe8019",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#1d2021",
          shapesColor: "#fe8019",
        },
        headingColor: "#fbf1c7",
        bioTextColor: "#ebdbb2",
      },
      linkStyle: {
        surfaceColor: "#282828",
        borderColor: "rgba(254, 128, 25, 0.35)",
        textColor: "#ebdbb2",
        subtextColor: "#fabd2f",
        iconColor: "#8ec07c",
        glowColor: "#fe8019",
        glowEnabled: true,
        glowOpacity: 60,
      },
    },
  },
  {
    id: "gruvbox-light",
    name: "Gruvbox Warm Parchment",
    category: "Developer",
    description: "Warm retro ivory parchment with rich burnt orange and moss green accents",
    previewColors: ["#fbf1c7", "#af3a03", "#79740e", "#ebdbb2"],
    accentColor: "#af3a03",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#fbf1c7",
          shapesColor: "#af3a03",
        },
        headingColor: "#3c3836",
        bioTextColor: "#7c6f64",
      },
      linkStyle: {
        surfaceColor: "#f2e5bc",
        borderColor: "rgba(175, 58, 3, 0.25)",
        textColor: "#282828",
        subtextColor: "#79740e",
        iconColor: "#af3a03",
        glowColor: "#d65d0e",
        glowEnabled: true,
        glowOpacity: 35,
      },
    },
  },
  {
    id: "solarized-dark",
    name: "Solarized Dark",
    category: "Developer",
    description: "Ethan Schoonover's legendary precision palette with cyan, yellow, and blue",
    previewColors: ["#002b36", "#2aa198", "#268bd2", "#073642"],
    accentColor: "#2aa198",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#002b36",
          shapesColor: "#2aa198",
        },
        headingColor: "#93a1a1",
        bioTextColor: "#2aa198",
      },
      linkStyle: {
        surfaceColor: "#073642",
        borderColor: "rgba(42, 161, 152, 0.35)",
        textColor: "#eee8d5",
        subtextColor: "#839496",
        iconColor: "#268bd2",
        glowColor: "#2aa198",
        glowEnabled: true,
        glowOpacity: 60,
      },
    },
  },
  {
    id: "solarized-light",
    name: "Solarized Warm Ivory",
    category: "Developer",
    description: "Calm, glare-reduced ivory reading palette with cyan and golden amber",
    previewColors: ["#fdf6e3", "#2aa198", "#b58900", "#eee8d5"],
    accentColor: "#2aa198",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#fdf6e3",
          shapesColor: "#2aa198",
        },
        headingColor: "#586e75",
        bioTextColor: "#657b83",
      },
      linkStyle: {
        surfaceColor: "#eee8d5",
        borderColor: "rgba(42, 161, 152, 0.25)",
        textColor: "#073642",
        subtextColor: "#b58900",
        iconColor: "#2aa198",
        glowColor: "#2aa198",
        glowEnabled: true,
        glowOpacity: 30,
      },
    },
  },
  {
    id: "kanagawa-wave",
    name: "Kanagawa Great Wave",
    category: "Developer",
    description: "Japanese ukiyo-e ink aesthetic with wave indigo, spring green, and autumn red",
    previewColors: ["#1f1f28", "#c34043", "#7e9cd8", "#98bb6c"],
    accentColor: "#7e9cd8",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#1f1f28",
          shapesColor: "#7e9cd8",
        },
        headingColor: "#dcd7ba",
        bioTextColor: "#98bb6c",
      },
      linkStyle: {
        surfaceColor: "#2a2a37",
        borderColor: "rgba(126, 156, 216, 0.3)",
        textColor: "#dcd7ba",
        subtextColor: "#957fb8",
        iconColor: "#c34043",
        glowColor: "#7e9cd8",
        glowEnabled: true,
        glowOpacity: 55,
      },
    },
  },
  {
    id: "rose-pine",
    name: "Rosé Pine Soho Dark",
    category: "Developer",
    description: "Muted luxury minimalism with desert rose, pine green, and foam teal",
    previewColors: ["#191724", "#ebbcba", "#9ccfd8", "#c4a7e7"],
    accentColor: "#ebbcba",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#191724",
          shapesColor: "#ebbcba",
        },
        headingColor: "#e0def4",
        bioTextColor: "#c4a7e7",
      },
      linkStyle: {
        surfaceColor: "#26233a",
        borderColor: "rgba(235, 188, 186, 0.3)",
        textColor: "#e0def4",
        subtextColor: "#9ccfd8",
        iconColor: "#ebbcba",
        glowColor: "#ebbcba",
        glowEnabled: true,
        glowOpacity: 55,
      },
    },
  },
  {
    id: "rose-pine-dawn",
    name: "Rosé Pine Dawn (Light)",
    category: "Developer",
    description: "Ethereal light botanical with warm desert rose, pine, and honey amber",
    previewColors: ["#faf4ed", "#d7827e", "#286983", "#ea9d34"],
    accentColor: "#d7827e",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#faf4ed",
          shapesColor: "#d7827e",
        },
        headingColor: "#575279",
        bioTextColor: "#797593",
      },
      linkStyle: {
        surfaceColor: "#fffaf3",
        borderColor: "rgba(215, 130, 126, 0.25)",
        textColor: "#575279",
        subtextColor: "#286983",
        iconColor: "#d7827e",
        glowColor: "#ea9d34",
        glowEnabled: true,
        glowOpacity: 35,
      },
    },
  },
  {
    id: "ayu-mirage",
    name: "Ayu Mirage Twilight",
    category: "Developer",
    description: "Twilight navy slate with warm sunrise gold and neon cyan highlights",
    previewColors: ["#1f2430", "#ffcc66", "#73d0ff", "#242936"],
    accentColor: "#ffcc66",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#1f2430",
          shapesColor: "#ffcc66",
        },
        headingColor: "#cbccc6",
        bioTextColor: "#73d0ff",
      },
      linkStyle: {
        surfaceColor: "#242936",
        borderColor: "rgba(255, 204, 102, 0.3)",
        textColor: "#ffffff",
        subtextColor: "#ffaa77",
        iconColor: "#ffcc66",
        glowColor: "#ffcc66",
        glowEnabled: true,
        glowOpacity: 60,
      },
    },
  },
  {
    id: "cobalt2",
    name: "Cobalt2 (Wes Bos)",
    category: "Developer",
    description: "Wes Bos signature theme: brilliant cobalt ocean with electric yellow pop",
    previewColors: ["#193549", "#ffc600", "#0088ff", "#15232d"],
    accentColor: "#ffc600",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#193549",
          gradientAngle: 150,
          gradientStops: [
            { color: "#152d3e", position: 0 },
            { color: "#193549", position: 50 },
            { color: "#102331", position: 100 },
          ],
          shapesColor: "#ffc600",
        },
        headingColor: "#ffffff",
        bioTextColor: "#ffc600",
      },
      linkStyle: {
        surfaceColor: "#112638",
        borderColor: "rgba(255, 198, 0, 0.35)",
        textColor: "#ffffff",
        subtextColor: "#0088ff",
        iconColor: "#ffc600",
        glowColor: "#ffc600",
        glowEnabled: true,
        glowOpacity: 65,
      },
    },
  },
  {
    id: "material-ocean",
    name: "Material Deep Ocean",
    category: "Developer",
    description: "Google Material inspired midnight navy with mint teal and lavender accents",
    previewColors: ["#0f111a", "#80cbc4", "#82aaff", "#1a1c25"],
    accentColor: "#80cbc4",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#0f111a",
          shapesColor: "#80cbc4",
        },
        headingColor: "#eeffff",
        bioTextColor: "#80cbc4",
      },
      linkStyle: {
        surfaceColor: "#1a1c25",
        borderColor: "rgba(128, 203, 196, 0.3)",
        textColor: "#eeffff",
        subtextColor: "#82aaff",
        iconColor: "#80cbc4",
        glowColor: "#80cbc4",
        glowEnabled: true,
        glowOpacity: 55,
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 2. DARK & STEALTH THEMES
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: "obsidian-violet",
    name: "Obsidian & Electric Violet",
    category: "Dark",
    description: "Deep stealth obsidian backdrop with high-contrast electric violet glow",
    previewColors: ["#0a0a14", "#8b5cf6", "#c4b5fd", "#151528"],
    accentColor: "#8b5cf6",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#0a0a14",
          gradientAngle: 135,
          gradientStops: [
            { color: "#090912", position: 0 },
            { color: "#120f26", position: 50 },
            { color: "#1c103f", position: 100 },
          ],
          shapesColor: "#8b5cf6",
        },
        headingColor: "#ffffff",
        bioTextColor: "#c4b5fd",
      },
      linkStyle: {
        surfaceColor: "#151528",
        borderColor: "rgba(139, 92, 246, 0.35)",
        textColor: "#ffffff",
        subtextColor: "#a78bfa",
        iconColor: "#c084fc",
        glowColor: "#8b5cf6",
        glowEnabled: true,
        glowOpacity: 65,
      },
    },
  },
  {
    id: "midnight-velvet",
    name: "Midnight Indigo Velvet",
    category: "Dark",
    description: "Deep royal navy blue with radiant indigo starlight accents",
    previewColors: ["#090d16", "#6366f1", "#38bdf8", "#1e293b"],
    accentColor: "#6366f1",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#070b14",
          gradientAngle: 145,
          gradientStops: [
            { color: "#070b14", position: 0 },
            { color: "#0f172a", position: 50 },
            { color: "#1e1b4b", position: 100 },
          ],
          shapesColor: "#6366f1",
        },
        headingColor: "#f8fafc",
        bioTextColor: "#94a3b8",
      },
      linkStyle: {
        surfaceColor: "#111827",
        borderColor: "rgba(99, 102, 241, 0.3)",
        textColor: "#ffffff",
        subtextColor: "#818cf8",
        iconColor: "#38bdf8",
        glowColor: "#6366f1",
        glowEnabled: true,
        glowOpacity: 60,
      },
    },
  },
  {
    id: "dracula-gothic",
    name: "Dracula Gothic Pro",
    category: "Dark",
    description: "The classic vampire palette: purple, soft pink, and eerie radioactive green",
    previewColors: ["#1e1f29", "#bd93f9", "#ff79c6", "#50fa7b"],
    accentColor: "#bd93f9",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#1e1f29",
          shapesColor: "#bd93f9",
        },
        headingColor: "#f8f8f2",
        bioTextColor: "#bd93f9",
      },
      linkStyle: {
        surfaceColor: "#282a36",
        borderColor: "rgba(189, 147, 249, 0.35)",
        textColor: "#f8f8f2",
        subtextColor: "#ff79c6",
        iconColor: "#50fa7b",
        glowColor: "#bd93f9",
        glowEnabled: true,
        glowOpacity: 65,
      },
    },
  },
  {
    id: "nordic-frost",
    name: "Nordic Arctic Frost",
    category: "Dark",
    description: "Crisp polar slate and glacial ice crystals inspired by Scandinavian winter",
    previewColors: ["#0b1320", "#38bdf8", "#7dd3fc", "#1e293b"],
    accentColor: "#38bdf8",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#0b1320",
          gradientAngle: 180,
          gradientStops: [
            { color: "#09101d", position: 0 },
            { color: "#0d1b2e", position: 50 },
            { color: "#062846", position: 100 },
          ],
          shapesColor: "#38bdf8",
        },
        headingColor: "#f0f9ff",
        bioTextColor: "#7dd3fc",
      },
      linkStyle: {
        surfaceColor: "#0f2338",
        borderColor: "rgba(56, 189, 248, 0.3)",
        textColor: "#ffffff",
        subtextColor: "#93c5fd",
        iconColor: "#38bdf8",
        glowColor: "#0284c7",
        glowEnabled: true,
        glowOpacity: 60,
      },
    },
  },
  {
    id: "ocean-abyss",
    name: "Deep Ocean Trench",
    category: "Dark",
    description: "Deep sea abyss navy glowing with bioluminescent aquamarine & cyan",
    previewColors: ["#020c1b", "#00f2fe", "#4facfe", "#0a2d52"],
    accentColor: "#00f2fe",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#020c1b",
          gradientAngle: 160,
          gradientStops: [
            { color: "#020c1b", position: 0 },
            { color: "#051f38", position: 50 },
            { color: "#083358", position: 100 },
          ],
          shapesColor: "#00f2fe",
        },
        headingColor: "#e0f2fe",
        bioTextColor: "#7dd3fc",
      },
      linkStyle: {
        surfaceColor: "#06223e",
        borderColor: "rgba(0, 242, 254, 0.3)",
        textColor: "#f0f9ff",
        subtextColor: "#38bdf8",
        iconColor: "#00f2fe",
        glowColor: "#0284c7",
        glowEnabled: true,
        glowOpacity: 65,
      },
    },
  },
  {
    id: "bumblebee-stealth",
    name: "Bumblebee Carbon Yellow",
    category: "Dark",
    description: "Striking high-visibility caution yellow on pitch-black carbon",
    previewColors: ["#0a0a0a", "#eab308", "#fde047", "#262626"],
    accentColor: "#eab308",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#0a0a0a",
          shapesColor: "#eab308",
        },
        headingColor: "#fef08a",
        bioTextColor: "#a1a1aa",
      },
      linkStyle: {
        surfaceColor: "#171717",
        borderColor: "rgba(234, 179, 8, 0.4)",
        textColor: "#ffffff",
        subtextColor: "#facc15",
        iconColor: "#eab308",
        glowColor: "#eab308",
        glowEnabled: true,
        glowOpacity: 65,
      },
    },
  },
  {
    id: "akane-crimson",
    name: "Akane Samurai Crimson",
    category: "Dark",
    description: "Deep obsidian shadows slashed with blood red neon and silver foil",
    previewColors: ["#09090b", "#ef4444", "#fca5a5", "#18181b"],
    accentColor: "#ef4444",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#09090b",
          gradientAngle: 155,
          gradientStops: [
            { color: "#09090b", position: 0 },
            { color: "#1c0d0f", position: 50 },
            { color: "#2e0b11", position: 100 },
          ],
          shapesColor: "#ef4444",
        },
        headingColor: "#fef2f2",
        bioTextColor: "#fca5a5",
      },
      linkStyle: {
        surfaceColor: "#1f0d11",
        borderColor: "rgba(239, 68, 68, 0.35)",
        textColor: "#ffffff",
        subtextColor: "#f87171",
        iconColor: "#ef4444",
        glowColor: "#ef4444",
        glowEnabled: true,
        glowOpacity: 65,
      },
    },
  },
  {
    id: "stealth-blackout",
    name: "Pure Stealth Blackout",
    category: "Dark",
    description: "Pure tactical blackout with subtle gunmetal edges and crisp white typography",
    previewColors: ["#050505", "#e2e8f0", "#94a3b8", "#121212"],
    accentColor: "#e2e8f0",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#050505",
          shapesColor: "#e2e8f0",
        },
        headingColor: "#f8fafc",
        bioTextColor: "#94a3b8",
      },
      linkStyle: {
        surfaceColor: "#121212",
        borderColor: "rgba(255, 255, 255, 0.12)",
        textColor: "#ffffff",
        subtextColor: "#64748b",
        iconColor: "#e2e8f0",
        glowColor: "#ffffff",
        glowEnabled: true,
        glowOpacity: 25,
      },
    },
  },
  {
    id: "midnight-plasma",
    name: "Midnight Electric Plasma",
    category: "Dark",
    description: "Deep space darkness ionized with high-energy purple plasma radiation",
    previewColors: ["#0b071e", "#8b5cf6", "#38bdf8", "#18103c"],
    accentColor: "#8b5cf6",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#0b071e",
          gradientAngle: 140,
          gradientStops: [
            { color: "#0b071e", position: 0 },
            { color: "#160e36", position: 50 },
            { color: "#250d4f", position: 100 },
          ],
          shapesColor: "#8b5cf6",
        },
        headingColor: "#f5f3ff",
        bioTextColor: "#38bdf8",
      },
      linkStyle: {
        surfaceColor: "#1c1242",
        borderColor: "rgba(139, 92, 246, 0.4)",
        textColor: "#ffffff",
        subtextColor: "#c4b5fd",
        iconColor: "#38bdf8",
        glowColor: "#8b5cf6",
        glowEnabled: true,
        glowOpacity: 70,
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 3. NEON & CYBERPUNK
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: "cyberpunk-2077",
    name: "Cyberpunk Cyan & Magenta",
    category: "Neon",
    description: "High-octane neon cyber colors straight out of Night City",
    previewColors: ["#080811", "#06b6d4", "#ec4899", "#22d3ee"],
    accentColor: "#06b6d4",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#080811",
          gradientAngle: 160,
          gradientStops: [
            { color: "#080811", position: 0 },
            { color: "#0a1526", position: 50 },
            { color: "#160721", position: 100 },
          ],
          shapesColor: "#06b6d4",
        },
        headingColor: "#22d3ee",
        bioTextColor: "#94a3b8",
      },
      linkStyle: {
        surfaceColor: "#0f172a",
        borderColor: "rgba(6, 182, 212, 0.4)",
        textColor: "#f8fafc",
        subtextColor: "#67e8f9",
        iconColor: "#ec4899",
        glowColor: "#06b6d4",
        glowEnabled: true,
        glowOpacity: 75,
      },
    },
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night Synth",
    category: "Neon",
    description: "Famous Tokyo developer theme with deep violet slate and cyan pop",
    previewColors: ["#1a1b26", "#9d7cd8", "#7dcfff", "#414868"],
    accentColor: "#7dcfff",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#1a1b26",
          shapesColor: "#9d7cd8",
        },
        headingColor: "#c0caf5",
        bioTextColor: "#a9b1d6",
      },
      linkStyle: {
        surfaceColor: "#24283b",
        borderColor: "rgba(125, 207, 255, 0.25)",
        textColor: "#c0caf5",
        subtextColor: "#7aa2f7",
        iconColor: "#7dcfff",
        glowColor: "#9d7cd8",
        glowEnabled: true,
        glowOpacity: 55,
      },
    },
  },
  {
    id: "matrix-hacker",
    name: "Matrix Phosphor Green",
    category: "Neon",
    description: "Classic CRT terminal aesthetic with glowing matrix green characters",
    previewColors: ["#020d06", "#22c55e", "#86efac", "#14532d"],
    accentColor: "#22c55e",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#020d06",
          shapesColor: "#22c55e",
        },
        headingColor: "#86efac",
        bioTextColor: "#4ade80",
      },
      linkStyle: {
        surfaceColor: "#062211",
        borderColor: "rgba(34, 197, 94, 0.4)",
        textColor: "#f0fdf4",
        subtextColor: "#86efac",
        iconColor: "#22c55e",
        glowColor: "#22c55e",
        glowEnabled: true,
        glowOpacity: 70,
      },
    },
  },
  {
    id: "acid-lime",
    name: "Acid Lime & Matte Carbon",
    category: "Neon",
    description: "High-contrast highlighter radioactive lime on stealth carbon black",
    previewColors: ["#0e0f10", "#a3e635", "#bef264", "#272a24"],
    accentColor: "#a3e635",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#0e0f10",
          shapesColor: "#a3e635",
        },
        headingColor: "#d9f99d",
        bioTextColor: "#a3e635",
      },
      linkStyle: {
        surfaceColor: "#181a17",
        borderColor: "rgba(163, 230, 53, 0.4)",
        textColor: "#ffffff",
        subtextColor: "#bef264",
        iconColor: "#a3e635",
        glowColor: "#a3e635",
        glowEnabled: true,
        glowOpacity: 70,
      },
    },
  },
  {
    id: "hyper-ultraviolet",
    name: "Hyper Ultraviolet Abyss",
    category: "Neon",
    description: "Deep space darkness saturated with hyper-intense neon purple light",
    previewColors: ["#080119", "#7c3aed", "#c084fc", "#4c1d95"],
    accentColor: "#7c3aed",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#080119",
          gradientAngle: 135,
          gradientStops: [
            { color: "#080119", position: 0 },
            { color: "#15042e", position: 50 },
            { color: "#24064a", position: 100 },
          ],
          shapesColor: "#7c3aed",
        },
        headingColor: "#f5f3ff",
        bioTextColor: "#c4b5fd",
      },
      linkStyle: {
        surfaceColor: "#1a0538",
        borderColor: "rgba(124, 58, 237, 0.4)",
        textColor: "#ffffff",
        subtextColor: "#a78bfa",
        iconColor: "#c084fc",
        glowColor: "#7c3aed",
        glowEnabled: true,
        glowOpacity: 70,
      },
    },
  },
  {
    id: "glitch-protocol",
    name: "Glitch Protocol Hot Pink",
    category: "Neon",
    description: "Cyber glitch aesthetic with hot fuchsia lasers and electric cyan pulses",
    previewColors: ["#0a0814", "#ff007f", "#00f0ff", "#2a1538"],
    accentColor: "#ff007f",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#0a0814",
          gradientAngle: 135,
          gradientStops: [
            { color: "#0a0814", position: 0 },
            { color: "#1d0c26", position: 50 },
            { color: "#2d0a33", position: 100 },
          ],
          shapesColor: "#ff007f",
        },
        headingColor: "#ffe4f1",
        bioTextColor: "#00f0ff",
      },
      linkStyle: {
        surfaceColor: "#22102e",
        borderColor: "rgba(255, 0, 127, 0.4)",
        textColor: "#ffffff",
        subtextColor: "#00f0ff",
        iconColor: "#ff007f",
        glowColor: "#ff007f",
        glowEnabled: true,
        glowOpacity: 75,
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 4. LUXURY, PRESTIGE & FASHION
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: "obsidian-gold",
    name: "Obsidian & 24K Gold",
    category: "Luxury",
    description: "Ultra-prestigious black tie luxury with 24-karat gold champagne accents",
    previewColors: ["#0d0d0d", "#f59e0b", "#fef08a", "#292218"],
    accentColor: "#f59e0b",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#0d0d0d",
          shapesColor: "#f59e0b",
        },
        headingColor: "#fef08a",
        bioTextColor: "#fde68a",
      },
      linkStyle: {
        surfaceColor: "#1c1917",
        borderColor: "rgba(245, 158, 11, 0.35)",
        textColor: "#fffbeb",
        subtextColor: "#fef08a",
        iconColor: "#f59e0b",
        glowColor: "#f59e0b",
        glowEnabled: true,
        glowOpacity: 60,
      },
    },
  },
  {
    id: "crimson-velvet",
    name: "Crimson Rose & Wine",
    category: "Luxury",
    description: "Rich Bordeaux wine depths with shimmering rose velvet accents",
    previewColors: ["#16040a", "#e11d48", "#fda4af", "#881337"],
    accentColor: "#e11d48",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#16040a",
          gradientAngle: 155,
          gradientStops: [
            { color: "#16040a", position: 0 },
            { color: "#2c0816", position: 50 },
            { color: "#3d0b1f", position: 100 },
          ],
          shapesColor: "#e11d48",
        },
        headingColor: "#fff1f2",
        bioTextColor: "#fecdd3",
      },
      linkStyle: {
        surfaceColor: "#290916",
        borderColor: "rgba(225, 29, 72, 0.35)",
        textColor: "#ffffff",
        subtextColor: "#fca5a5",
        iconColor: "#fda4af",
        glowColor: "#e11d48",
        glowEnabled: true,
        glowOpacity: 65,
      },
    },
  },
  {
    id: "royal-amethyst",
    name: "Royal Imperial Amethyst",
    category: "Luxury",
    description: "Regal imperial purple gem tones with polished amethyst crystal aura",
    previewColors: ["#130722", "#9333ea", "#f3e8ff", "#581c87"],
    accentColor: "#9333ea",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#130722",
          gradientAngle: 135,
          gradientStops: [
            { color: "#130722", position: 0 },
            { color: "#230b3d", position: 50 },
            { color: "#36105c", position: 100 },
          ],
          shapesColor: "#9333ea",
        },
        headingColor: "#f3e8ff",
        bioTextColor: "#d8b4fe",
      },
      linkStyle: {
        surfaceColor: "#250d3e",
        borderColor: "rgba(147, 51, 234, 0.35)",
        textColor: "#ffffff",
        subtextColor: "#c084fc",
        iconColor: "#d8b4fe",
        glowColor: "#9333ea",
        glowEnabled: true,
        glowOpacity: 65,
      },
    },
  },
  {
    id: "tiffany-turquoise",
    name: "Tiffany Robin Egg Luxury",
    category: "Luxury",
    description: "World-famous Tiffany robin egg blue with dark emerald silk and silver",
    previewColors: ["#052021", "#0abab5", "#e2f9f8", "#0a3a3d"],
    accentColor: "#0abab5",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#052021",
          gradientAngle: 145,
          gradientStops: [
            { color: "#041b1c", position: 0 },
            { color: "#072b2d", position: 50 },
            { color: "#0b393c", position: 100 },
          ],
          shapesColor: "#0abab5",
        },
        headingColor: "#e2f9f8",
        bioTextColor: "#80ded9",
      },
      linkStyle: {
        surfaceColor: "#093336",
        borderColor: "rgba(10, 186, 181, 0.35)",
        textColor: "#ffffff",
        subtextColor: "#a5f3fc",
        iconColor: "#0abab5",
        glowColor: "#0abab5",
        glowEnabled: true,
        glowOpacity: 65,
      },
    },
  },
  {
    id: "hermes-leather",
    name: "Hermès Orange & Espresso",
    category: "Luxury",
    description: "Iconic Parisian luxury leather orange paired with deep roasted espresso",
    previewColors: ["#180a04", "#f95700", "#fed7aa", "#38190c"],
    accentColor: "#f95700",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#180a04",
          gradientAngle: 140,
          gradientStops: [
            { color: "#180a04", position: 0 },
            { color: "#261007", position: 50 },
            { color: "#3d190b", position: 100 },
          ],
          shapesColor: "#f95700",
        },
        headingColor: "#fff7ed",
        bioTextColor: "#fed7aa",
      },
      linkStyle: {
        surfaceColor: "#281208",
        borderColor: "rgba(249, 87, 0, 0.35)",
        textColor: "#ffffff",
        subtextColor: "#fdba74",
        iconColor: "#f95700",
        glowColor: "#f95700",
        glowEnabled: true,
        glowOpacity: 60,
      },
    },
  },
  {
    id: "chanel-monochrome",
    name: "Chanel Noir & Blanc",
    category: "Luxury",
    description: "Pure timeless Parisian haute couture in stark black and pearl white",
    previewColors: ["#000000", "#ffffff", "#e2e8f0", "#1c1c1c"],
    accentColor: "#ffffff",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#000000",
          shapesColor: "#ffffff",
        },
        headingColor: "#ffffff",
        bioTextColor: "#cbd5e1",
      },
      linkStyle: {
        surfaceColor: "#141414",
        borderColor: "rgba(255, 255, 255, 0.2)",
        textColor: "#ffffff",
        subtextColor: "#94a3b8",
        iconColor: "#ffffff",
        glowColor: "#ffffff",
        glowEnabled: true,
        glowOpacity: 30,
      },
    },
  },
  {
    id: "cartier-emerald",
    name: "Cartier Emerald & 18K Gold",
    category: "Luxury",
    description: "High jewelry green velvet with brilliant 18k yellow gold filigree",
    previewColors: ["#03170e", "#10b981", "#f59e0b", "#083321"],
    accentColor: "#f59e0b",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#03170e",
          gradientAngle: 150,
          gradientStops: [
            { color: "#03170e", position: 0 },
            { color: "#062b1b", position: 50 },
            { color: "#0c3d27", position: 100 },
          ],
          shapesColor: "#f59e0b",
        },
        headingColor: "#fef3c7",
        bioTextColor: "#a7f3d0",
      },
      linkStyle: {
        surfaceColor: "#082d1c",
        borderColor: "rgba(245, 158, 11, 0.35)",
        textColor: "#ffffff",
        subtextColor: "#fde68a",
        iconColor: "#f59e0b",
        glowColor: "#f59e0b",
        glowEnabled: true,
        glowOpacity: 60,
      },
    },
  },
  {
    id: "royal-sapphire",
    name: "Royal Sapphire & Diamond",
    category: "Luxury",
    description: "Imperial British coronation blue with radiant white diamond sparkles",
    previewColors: ["#050d24", "#2563eb", "#e2e8f0", "#0c1a40"],
    accentColor: "#2563eb",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#050d24",
          gradientAngle: 145,
          gradientStops: [
            { color: "#050d24", position: 0 },
            { color: "#0a1738", position: 50 },
            { color: "#112659", position: 100 },
          ],
          shapesColor: "#2563eb",
        },
        headingColor: "#eff6ff",
        bioTextColor: "#bfdbfe",
      },
      linkStyle: {
        surfaceColor: "#0e1f4a",
        borderColor: "rgba(37, 99, 235, 0.35)",
        textColor: "#ffffff",
        subtextColor: "#93c5fd",
        iconColor: "#60a5fa",
        glowColor: "#2563eb",
        glowEnabled: true,
        glowOpacity: 65,
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 5. NATURE, BOTANICAL & EARTH
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: "emerald-matcha",
    name: "Matcha Botanical Zen",
    category: "Nature",
    description: "Calming forest emerald, sage herbs, and tranquil tea greens",
    previewColors: ["#06150f", "#10b981", "#34d399", "#064e3b"],
    accentColor: "#10b981",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#05130d",
          gradientAngle: 155,
          gradientStops: [
            { color: "#05130d", position: 0 },
            { color: "#08241a", position: 50 },
            { color: "#0c3b2b", position: 100 },
          ],
          shapesColor: "#10b981",
        },
        headingColor: "#ecfdf5",
        bioTextColor: "#a7f3d0",
      },
      linkStyle: {
        surfaceColor: "#064e3b",
        borderColor: "rgba(52, 211, 153, 0.3)",
        textColor: "#f0fdf4",
        subtextColor: "#6ee7b7",
        iconColor: "#34d399",
        glowColor: "#10b981",
        glowEnabled: true,
        glowOpacity: 55,
      },
    },
  },
  {
    id: "terracotta-canyon",
    name: "Terracotta Desert Canyon",
    category: "Nature",
    description: "Sunbaked earth tones, warm rust terracotta, and southwest gold",
    previewColors: ["#190c07", "#ea580c", "#f59e0b", "#7c2d12"],
    accentColor: "#ea580c",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#190c07",
          gradientAngle: 145,
          gradientStops: [
            { color: "#190c07", position: 0 },
            { color: "#2d160d", position: 50 },
            { color: "#3d1b0d", position: 100 },
          ],
          shapesColor: "#ea580c",
        },
        headingColor: "#ffedd5",
        bioTextColor: "#fed7aa",
      },
      linkStyle: {
        surfaceColor: "#2e150d",
        borderColor: "rgba(234, 88, 12, 0.35)",
        textColor: "#ffffff",
        subtextColor: "#fdba74",
        iconColor: "#f59e0b",
        glowColor: "#ea580c",
        glowEnabled: true,
        glowOpacity: 55,
      },
    },
  },
  {
    id: "espresso-roast",
    name: "Dark Espresso & Roasted Amber",
    category: "Nature",
    description: "Rich dark Italian roast with caramelized crema and amber warmth",
    previewColors: ["#140b08", "#b45309", "#fef3c7", "#78350f"],
    accentColor: "#b45309",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#140b08",
          gradientAngle: 140,
          gradientStops: [
            { color: "#140b08", position: 0 },
            { color: "#24130d", position: 50 },
            { color: "#331a10", position: 100 },
          ],
          shapesColor: "#b45309",
        },
        headingColor: "#fef3c7",
        bioTextColor: "#fed7aa",
      },
      linkStyle: {
        surfaceColor: "#26150e",
        borderColor: "rgba(180, 83, 9, 0.35)",
        textColor: "#ffffff",
        subtextColor: "#fde68a",
        iconColor: "#d97706",
        glowColor: "#b45309",
        glowEnabled: true,
        glowOpacity: 55,
      },
    },
  },
  {
    id: "mint-mojito",
    name: "Mint Mojito & Deep Teal",
    category: "Nature",
    description: "Crisp tropical spearmint on deep midnight teal waters",
    previewColors: ["#041615", "#14b8a6", "#a3e635", "#0f766e"],
    accentColor: "#14b8a6",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#041615",
          gradientAngle: 155,
          gradientStops: [
            { color: "#041615", position: 0 },
            { color: "#082725", position: 50 },
            { color: "#0c3b38", position: 100 },
          ],
          shapesColor: "#14b8a6",
        },
        headingColor: "#ccfbf1",
        bioTextColor: "#5eead4",
      },
      linkStyle: {
        surfaceColor: "#082d2b",
        borderColor: "rgba(20, 184, 166, 0.35)",
        textColor: "#ffffff",
        subtextColor: "#99f6e4",
        iconColor: "#2dd4bf",
        glowColor: "#14b8a6",
        glowEnabled: true,
        glowOpacity: 60,
      },
    },
  },
  {
    id: "eucalyptus-sage",
    name: "Misty Eucalyptus & Sage",
    category: "Nature",
    description: "Dewy Australian eucalyptus leaves and soothing pale sage botanicals",
    previewColors: ["#0a1612", "#84cc16", "#a3e635", "#142e24"],
    accentColor: "#84cc16",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#0a1612",
          gradientAngle: 145,
          gradientStops: [
            { color: "#0a1612", position: 0 },
            { color: "#11241e", position: 50 },
            { color: "#18362d", position: 100 },
          ],
          shapesColor: "#84cc16",
        },
        headingColor: "#ecfccb",
        bioTextColor: "#bef264",
      },
      linkStyle: {
        surfaceColor: "#122a22",
        borderColor: "rgba(132, 204, 22, 0.3)",
        textColor: "#ffffff",
        subtextColor: "#bef264",
        iconColor: "#a3e635",
        glowColor: "#84cc16",
        glowEnabled: true,
        glowOpacity: 55,
      },
    },
  },
  {
    id: "nordic-pine",
    name: "Nordic Pine Forest",
    category: "Nature",
    description: "Deep Scandinavian evergreen canopy with cold mountain air accents",
    previewColors: ["#04140b", "#22c55e", "#86efac", "#0c2e1c"],
    accentColor: "#22c55e",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#04140b",
          shapesColor: "#22c55e",
        },
        headingColor: "#dcfce7",
        bioTextColor: "#86efac",
      },
      linkStyle: {
        surfaceColor: "#0c2818",
        borderColor: "rgba(34, 197, 94, 0.3)",
        textColor: "#ffffff",
        subtextColor: "#86efac",
        iconColor: "#22c55e",
        glowColor: "#22c55e",
        glowEnabled: true,
        glowOpacity: 55,
      },
    },
  },
  {
    id: "autumn-maple",
    name: "Autumn Maple Leaves",
    category: "Nature",
    description: "New England fall foliage: fiery maple red, chestnut, and golden oak",
    previewColors: ["#1c0808", "#dc2626", "#f97316", "#3b1212"],
    accentColor: "#f97316",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#1c0808",
          gradientAngle: 140,
          gradientStops: [
            { color: "#1c0808", position: 0 },
            { color: "#2d0e0e", position: 50 },
            { color: "#421313", position: 100 },
          ],
          shapesColor: "#f97316",
        },
        headingColor: "#fef2f2",
        bioTextColor: "#fed7aa",
      },
      linkStyle: {
        surfaceColor: "#2e0f0f",
        borderColor: "rgba(249, 115, 22, 0.35)",
        textColor: "#ffffff",
        subtextColor: "#fdba74",
        iconColor: "#dc2626",
        glowColor: "#f97316",
        glowEnabled: true,
        glowOpacity: 60,
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 6. AESTHETIC & PASTEL DREAM
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: "cotton-candy-pastel",
    name: "Cotton Candy & Sweet Plum",
    category: "Pastel",
    description: "Whimsical dreamscape of soft candy pink and baby cyan clouds",
    previewColors: ["#160f24", "#f472b6", "#67e8f9", "#c084fc"],
    accentColor: "#f472b6",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#160f24",
          gradientAngle: 135,
          gradientStops: [
            { color: "#160f24", position: 0 },
            { color: "#281232", position: 50 },
            { color: "#1a1236", position: 100 },
          ],
          shapesColor: "#f472b6",
        },
        headingColor: "#fdf2f8",
        bioTextColor: "#f5d0fe",
      },
      linkStyle: {
        surfaceColor: "#271638",
        borderColor: "rgba(244, 114, 182, 0.3)",
        textColor: "#ffffff",
        subtextColor: "#f0abfc",
        iconColor: "#67e8f9",
        glowColor: "#f472b6",
        glowEnabled: true,
        glowOpacity: 60,
      },
    },
  },
  {
    id: "catppuccin-mocha",
    name: "Catppuccin Mocha",
    category: "Pastel",
    description: "Soothing pastel dark aesthetic loved by designers & developers worldwide",
    previewColors: ["#1e1e2e", "#cba6f7", "#74c7ec", "#f5e0dc"],
    accentColor: "#cba6f7",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#1e1e2e",
          shapesColor: "#cba6f7",
        },
        headingColor: "#cdd6f4",
        bioTextColor: "#bac2de",
      },
      linkStyle: {
        surfaceColor: "#313244",
        borderColor: "rgba(203, 166, 247, 0.3)",
        textColor: "#cdd6f4",
        subtextColor: "#74c7ec",
        iconColor: "#cba6f7",
        glowColor: "#cba6f7",
        glowEnabled: true,
        glowOpacity: 55,
      },
    },
  },
  {
    id: "lavender-haze",
    name: "Lavender Twilight Haze",
    category: "Pastel",
    description: "Ethereal twilight purple mist with soft wisteria and blush lavender",
    previewColors: ["#120e24", "#c084fc", "#f472b6", "#a855f7"],
    accentColor: "#c084fc",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#120e24",
          gradientAngle: 135,
          gradientStops: [
            { color: "#120e24", position: 0 },
            { color: "#1c1438", position: 50 },
            { color: "#25123d", position: 100 },
          ],
          shapesColor: "#c084fc",
        },
        headingColor: "#f3e8ff",
        bioTextColor: "#d8b4fe",
      },
      linkStyle: {
        surfaceColor: "#22173b",
        borderColor: "rgba(192, 132, 252, 0.3)",
        textColor: "#ffffff",
        subtextColor: "#e9d5ff",
        iconColor: "#c084fc",
        glowColor: "#a855f7",
        glowEnabled: true,
        glowOpacity: 60,
      },
    },
  },
  {
    id: "sakura-night",
    name: "Midnight Sakura Bloom",
    category: "Pastel",
    description: "Moonlit Tokyo cherry blossoms with dark plum shadows and soft petals",
    previewColors: ["#180914", "#fb7185", "#fff1f2", "#f43f5e"],
    accentColor: "#fb7185",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#180914",
          gradientAngle: 150,
          gradientStops: [
            { color: "#180914", position: 0 },
            { color: "#280e22", position: 50 },
            { color: "#36102a", position: 100 },
          ],
          shapesColor: "#fb7185",
        },
        headingColor: "#fff1f2",
        bioTextColor: "#fecdd3",
      },
      linkStyle: {
        surfaceColor: "#2d0f25",
        borderColor: "rgba(251, 113, 133, 0.35)",
        textColor: "#ffffff",
        subtextColor: "#fda4af",
        iconColor: "#fb7185",
        glowColor: "#f43f5e",
        glowEnabled: true,
        glowOpacity: 60,
      },
    },
  },
  {
    id: "strawberry-milk",
    name: "Strawberry Milkshake",
    category: "Pastel",
    description: "Creamy diner strawberry shake with whipped cream and sweet candy sprinkles",
    previewColors: ["#1c0a14", "#f43f5e", "#fbcfe8", "#2e1222"],
    accentColor: "#f43f5e",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#1c0a14",
          gradientAngle: 145,
          gradientStops: [
            { color: "#1c0a14", position: 0 },
            { color: "#2d1020", position: 50 },
            { color: "#3a1329", position: 100 },
          ],
          shapesColor: "#f43f5e",
        },
        headingColor: "#fff1f2",
        bioTextColor: "#fbcfe8",
      },
      linkStyle: {
        surfaceColor: "#2e1222",
        borderColor: "rgba(244, 63, 94, 0.3)",
        textColor: "#ffffff",
        subtextColor: "#fda4af",
        iconColor: "#f43f5e",
        glowColor: "#f43f5e",
        glowEnabled: true,
        glowOpacity: 60,
      },
    },
  },
  {
    id: "taro-boba",
    name: "Taro Milk Tea & Boba",
    category: "Pastel",
    description: "Sweet creamy Taiwanese taro root purple with velvet brown sugar pearls",
    previewColors: ["#160e22", "#c084fc", "#e9d5ff", "#251838"],
    accentColor: "#c084fc",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#160e22",
          gradientAngle: 135,
          gradientStops: [
            { color: "#160e22", position: 0 },
            { color: "#231636", position: 50 },
            { color: "#311f4a", position: 100 },
          ],
          shapesColor: "#c084fc",
        },
        headingColor: "#f5f3ff",
        bioTextColor: "#d8b4fe",
      },
      linkStyle: {
        surfaceColor: "#27193b",
        borderColor: "rgba(192, 132, 252, 0.3)",
        textColor: "#ffffff",
        subtextColor: "#e9d5ff",
        iconColor: "#c084fc",
        glowColor: "#c084fc",
        glowEnabled: true,
        glowOpacity: 55,
      },
    },
  },
  {
    id: "pistachio-gelato",
    name: "Pistachio Cream Gelato",
    category: "Pastel",
    description: "Italian artisan pale pistachio green with crushed toasted hazelnut notes",
    previewColors: ["#0f1712", "#86efac", "#dcfce7", "#1c2b22"],
    accentColor: "#86efac",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#0f1712",
          shapesColor: "#86efac",
        },
        headingColor: "#f0fdf4",
        bioTextColor: "#86efac",
      },
      linkStyle: {
        surfaceColor: "#1c2b22",
        borderColor: "rgba(134, 239, 172, 0.3)",
        textColor: "#ffffff",
        subtextColor: "#bbf7d0",
        iconColor: "#86efac",
        glowColor: "#86efac",
        glowEnabled: true,
        glowOpacity: 50,
      },
    },
  },
  {
    id: "baby-blue-cloud",
    name: "Baby Blue Cloud Nine",
    category: "Pastel",
    description: "Soft powder sky blue with fluffy marshmallow clouds and gentle morning light",
    previewColors: ["#0a1424", "#60a5fa", "#bfdbfe", "#13243d"],
    accentColor: "#60a5fa",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#0a1424",
          gradientAngle: 150,
          gradientStops: [
            { color: "#0a1424", position: 0 },
            { color: "#102038", position: 50 },
            { color: "#162e52", position: 100 },
          ],
          shapesColor: "#60a5fa",
        },
        headingColor: "#f0f9ff",
        bioTextColor: "#bfdbfe",
      },
      linkStyle: {
        surfaceColor: "#132745",
        borderColor: "rgba(96, 165, 250, 0.3)",
        textColor: "#ffffff",
        subtextColor: "#93c5fd",
        iconColor: "#60a5fa",
        glowColor: "#60a5fa",
        glowEnabled: true,
        glowOpacity: 55,
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 7. VIBRANT & POP
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: "sunset-peach",
    name: "Sunset Tangerine & Coral",
    category: "Vibrant",
    description: "Golden hour dusk sky blending warm tangerine, peach, and coral rose",
    previewColors: ["#190918", "#f97316", "#fb7185", "#fb923c"],
    accentColor: "#f97316",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#190918",
          gradientAngle: 135,
          gradientStops: [
            { color: "#190918", position: 0 },
            { color: "#2d0f21", position: 50 },
            { color: "#4a121d", position: 100 },
          ],
          shapesColor: "#f97316",
        },
        headingColor: "#fff1f2",
        bioTextColor: "#fed7aa",
      },
      linkStyle: {
        surfaceColor: "#2e0f22",
        borderColor: "rgba(249, 115, 22, 0.35)",
        textColor: "#ffffff",
        subtextColor: "#fca5a5",
        iconColor: "#fb923c",
        glowColor: "#f97316",
        glowEnabled: true,
        glowOpacity: 65,
      },
    },
  },
  {
    id: "retro-synthwave",
    name: "80s Retro Synthwave",
    category: "Vibrant",
    description: "Outrun neon highway glow with hot fuchsia and electric solar orange",
    previewColors: ["#14052b", "#d946ef", "#f97316", "#06b6d4"],
    accentColor: "#d946ef",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#14052b",
          gradientAngle: 180,
          gradientStops: [
            { color: "#14052b", position: 0 },
            { color: "#280738", position: 60 },
            { color: "#450a2b", position: 100 },
          ],
          shapesColor: "#d946ef",
        },
        headingColor: "#fae8ff",
        bioTextColor: "#f0abfc",
      },
      linkStyle: {
        surfaceColor: "#2a0845",
        borderColor: "rgba(217, 70, 239, 0.4)",
        textColor: "#ffffff",
        subtextColor: "#fed7aa",
        iconColor: "#f97316",
        glowColor: "#d946ef",
        glowEnabled: true,
        glowOpacity: 70,
      },
    },
  },
  {
    id: "cosmic-nebula",
    name: "Cosmic Nebula Galactic",
    category: "Vibrant",
    description: "Interstellar space stardust with electric magenta and cyan auroras",
    previewColors: ["#080318", "#a855f7", "#38bdf8", "#d946ef"],
    accentColor: "#d946ef",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#080318",
          gradientAngle: 135,
          gradientStops: [
            { color: "#080318", position: 0 },
            { color: "#190833", position: 50 },
            { color: "#2d083d", position: 100 },
          ],
          shapesColor: "#a855f7",
        },
        headingColor: "#fdf4ff",
        bioTextColor: "#d8b4fe",
      },
      linkStyle: {
        surfaceColor: "#1f0938",
        borderColor: "rgba(217, 70, 239, 0.35)",
        textColor: "#ffffff",
        subtextColor: "#67e8f9",
        iconColor: "#d946ef",
        glowColor: "#a855f7",
        glowEnabled: true,
        glowOpacity: 65,
      },
    },
  },
  {
    id: "solar-inferno",
    name: "Solar Magma Inferno",
    category: "Vibrant",
    description: "Blazing solar flares, fiery volcanic magma, and electric molten amber",
    previewColors: ["#160402", "#f97316", "#fde047", "#7c2d12"],
    accentColor: "#f97316",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#160402",
          gradientAngle: 135,
          gradientStops: [
            { color: "#160402", position: 0 },
            { color: "#290804", position: 50 },
            { color: "#400e07", position: 100 },
          ],
          shapesColor: "#f97316",
        },
        headingColor: "#fff7ed",
        bioTextColor: "#fed7aa",
      },
      linkStyle: {
        surfaceColor: "#2e0b06",
        borderColor: "rgba(249, 115, 22, 0.4)",
        textColor: "#ffffff",
        subtextColor: "#fde047",
        iconColor: "#f97316",
        glowColor: "#ea580c",
        glowEnabled: true,
        glowOpacity: 70,
      },
    },
  },
  {
    id: "miami-vice-84",
    name: "Miami Vice Neon Sunset",
    category: "Vibrant",
    description: "Iconic South Beach palm tree aesthetic with neon flamingo pink and lagoon teal",
    previewColors: ["#18062b", "#f43f5e", "#06b6d4", "#2b0b4d"],
    accentColor: "#f43f5e",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#18062b",
          gradientAngle: 160,
          gradientStops: [
            { color: "#18062b", position: 0 },
            { color: "#290938", position: 50 },
            { color: "#3d0a3d", position: 100 },
          ],
          shapesColor: "#f43f5e",
        },
        headingColor: "#ffe4f1",
        bioTextColor: "#22d3ee",
      },
      linkStyle: {
        surfaceColor: "#29093d",
        borderColor: "rgba(244, 63, 94, 0.4)",
        textColor: "#ffffff",
        subtextColor: "#67e8f9",
        iconColor: "#f43f5e",
        glowColor: "#06b6d4",
        glowEnabled: true,
        glowOpacity: 70,
      },
    },
  },
  {
    id: "pop-art-warhol",
    name: "Pop Art Andy Warhol",
    category: "Vibrant",
    description: "Bold pop art energy with primary yellow, vivid crimson, and ultramarine blue",
    previewColors: ["#141005", "#eab308", "#ef4444", "#3b82f6"],
    accentColor: "#eab308",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#141005",
          shapesColor: "#eab308",
        },
        headingColor: "#fef08a",
        bioTextColor: "#93c5fd",
      },
      linkStyle: {
        surfaceColor: "#241a08",
        borderColor: "rgba(234, 179, 8, 0.4)",
        textColor: "#ffffff",
        subtextColor: "#fca5a5",
        iconColor: "#ef4444",
        glowColor: "#eab308",
        glowEnabled: true,
        glowOpacity: 65,
      },
    },
  },
  {
    id: "aurora-borealis",
    name: "Aurora Borealis Northern Lights",
    category: "Vibrant",
    description: "Curtain of dancing green and violet starlight across a pitch-black polar sky",
    previewColors: ["#041416", "#10b981", "#8b5cf6", "#092e31"],
    accentColor: "#10b981",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#041416",
          gradientAngle: 135,
          gradientStops: [
            { color: "#041416", position: 0 },
            { color: "#082928", position: 50 },
            { color: "#191238", position: 100 },
          ],
          shapesColor: "#10b981",
        },
        headingColor: "#d1fae5",
        bioTextColor: "#c4b5fd",
      },
      linkStyle: {
        surfaceColor: "#0a2d2a",
        borderColor: "rgba(16, 185, 129, 0.35)",
        textColor: "#ffffff",
        subtextColor: "#a78bfa",
        iconColor: "#10b981",
        glowColor: "#8b5cf6",
        glowEnabled: true,
        glowOpacity: 70,
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 8. CLEAN & MINIMAL LIGHT MODES
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: "milk-and-honey",
    name: "Milk & Warm Honey (Light)",
    category: "Light",
    description: "Warm artisanal cream background with golden wildflower honey notes",
    previewColors: ["#faf8f5", "#d97706", "#292524", "#fef3c7"],
    accentColor: "#d97706",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#fbf9f5",
          shapesColor: "#d97706",
        },
        headingColor: "#292524",
        bioTextColor: "#78716c",
      },
      linkStyle: {
        surfaceColor: "#ffffff",
        borderColor: "rgba(217, 119, 6, 0.25)",
        textColor: "#1c1917",
        subtextColor: "#78716c",
        iconColor: "#d97706",
        glowColor: "#fbbf24",
        glowEnabled: true,
        glowOpacity: 35,
      },
    },
  },
  {
    id: "blush-champagne",
    name: "Blush Champagne & Rose (Light)",
    category: "Light",
    description: "Editorial luxury aesthetic with delicate alabaster and rose gold elegance",
    previewColors: ["#fdfaf9", "#e11d48", "#1e293b", "#ffe4e6"],
    accentColor: "#e11d48",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#faf5f5",
          shapesColor: "#e11d48",
        },
        headingColor: "#1e293b",
        bioTextColor: "#64748b",
      },
      linkStyle: {
        surfaceColor: "#ffffff",
        borderColor: "rgba(225, 29, 72, 0.2)",
        textColor: "#0f172a",
        subtextColor: "#64748b",
        iconColor: "#e11d48",
        glowColor: "#fda4af",
        glowEnabled: true,
        glowOpacity: 30,
      },
    },
  },
  {
    id: "nordic-snow",
    name: "Nordic Snow & Cobalt (Light)",
    category: "Light",
    description: "Crisp snowy silver backdrop with pure electric cobalt accents",
    previewColors: ["#f4f7fb", "#2563eb", "#0f172a", "#dbeafe"],
    accentColor: "#2563eb",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#f1f5f9",
          shapesColor: "#2563eb",
        },
        headingColor: "#0f172a",
        bioTextColor: "#475569",
      },
      linkStyle: {
        surfaceColor: "#ffffff",
        borderColor: "rgba(37, 99, 235, 0.2)",
        textColor: "#0f172a",
        subtextColor: "#64748b",
        iconColor: "#2563eb",
        glowColor: "#60a5fa",
        glowEnabled: true,
        glowOpacity: 35,
      },
    },
  },
  {
    id: "editorial-paper",
    name: "Editorial Paper & Charcoal (Light)",
    category: "Light",
    description: "Classic typography book reader cream with high-contrast printer ink",
    previewColors: ["#fbfaf8", "#c2410c", "#1c1917", "#f5f3ef"],
    accentColor: "#c2410c",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#fcfbf9",
          shapesColor: "#c2410c",
        },
        headingColor: "#1c1917",
        bioTextColor: "#57534e",
      },
      linkStyle: {
        surfaceColor: "#ffffff",
        borderColor: "rgba(28, 25, 23, 0.15)",
        textColor: "#1c1917",
        subtextColor: "#78716c",
        iconColor: "#c2410c",
        glowColor: "#ea580c",
        glowEnabled: true,
        glowOpacity: 25,
      },
    },
  },
  {
    id: "apple-cupertino",
    name: "Cupertino Clean Silver (Light)",
    category: "Light",
    description: "Ultra-pure Apple UI aesthetic with frosted white acrylic and system blue",
    previewColors: ["#f5f5f7", "#0071e3", "#1d1d1f", "#ffffff"],
    accentColor: "#0071e3",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#f5f5f7",
          shapesColor: "#0071e3",
        },
        headingColor: "#1d1d1f",
        bioTextColor: "#6e6e73",
      },
      linkStyle: {
        surfaceColor: "#ffffff",
        borderColor: "rgba(0, 113, 227, 0.18)",
        textColor: "#1d1d1f",
        subtextColor: "#6e6e73",
        iconColor: "#0071e3",
        glowColor: "#0071e3",
        glowEnabled: true,
        glowOpacity: 25,
      },
    },
  },
  {
    id: "oat-milk-latte",
    name: "Oat Milk Latte (Light)",
    category: "Light",
    description: "Cozy café aesthetic with oat milk foam, cinnamon bark, and rich hazelnut",
    previewColors: ["#f8f6f0", "#b45309", "#44403c", "#ede8dc"],
    accentColor: "#b45309",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#f7f5ef",
          shapesColor: "#b45309",
        },
        headingColor: "#292524",
        bioTextColor: "#57534e",
      },
      linkStyle: {
        surfaceColor: "#ffffff",
        borderColor: "rgba(180, 83, 9, 0.2)",
        textColor: "#292524",
        subtextColor: "#78716c",
        iconColor: "#b45309",
        glowColor: "#d97706",
        glowEnabled: true,
        glowOpacity: 30,
      },
    },
  },
  {
    id: "sakura-silk-light",
    name: "Sakura Silk Petal (Light)",
    category: "Light",
    description: "Delicate spring morning cherry blossom silk with sweet rose quartz",
    previewColors: ["#fff5f6", "#e11d48", "#4c0519", "#ffe3e6"],
    accentColor: "#e11d48",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#fff5f6",
          shapesColor: "#e11d48",
        },
        headingColor: "#4c0519",
        bioTextColor: "#881337",
      },
      linkStyle: {
        surfaceColor: "#ffffff",
        borderColor: "rgba(225, 29, 72, 0.2)",
        textColor: "#4c0519",
        subtextColor: "#9f1239",
        iconColor: "#e11d48",
        glowColor: "#fb7185",
        glowEnabled: true,
        glowOpacity: 30,
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 9. MINIMAL & MONOCHROME
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: "minimal-slate",
    name: "Minimalist Slate & Silver",
    category: "Minimal",
    description: "Clean, distraction-free architectural dark slate with crisp silver text",
    previewColors: ["#0b0f19", "#ffffff", "#94a3b8", "#1e293b"],
    accentColor: "#ffffff",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#0b0f19",
          shapesColor: "#ffffff",
        },
        headingColor: "#ffffff",
        bioTextColor: "#94a3b8",
      },
      linkStyle: {
        surfaceColor: "#161f30",
        borderColor: "rgba(255, 255, 255, 0.15)",
        textColor: "#ffffff",
        subtextColor: "#94a3b8",
        iconColor: "#ffffff",
        glowColor: "#ffffff",
        glowEnabled: false,
        glowOpacity: 25,
      },
    },
  },
  {
    id: "carbon-graphite",
    name: "Carbon Graphite Monolith",
    category: "Minimal",
    description: "Understated industrial graphite with precision engineered matte grey borders",
    previewColors: ["#121214", "#71717a", "#e4e4e7", "#1c1c1f"],
    accentColor: "#e4e4e7",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#121214",
          shapesColor: "#71717a",
        },
        headingColor: "#f4f4f5",
        bioTextColor: "#a1a1aa",
      },
      linkStyle: {
        surfaceColor: "#1a1a1e",
        borderColor: "rgba(255, 255, 255, 0.1)",
        textColor: "#f4f4f5",
        subtextColor: "#71717a",
        iconColor: "#e4e4e7",
        glowColor: "#a1a1aa",
        glowEnabled: false,
        glowOpacity: 20,
      },
    },
  },
  {
    id: "swiss-monochrome",
    name: "Swiss International Style",
    category: "Minimal",
    description: "Classic 1950s Zurich design: stark grid, pure contrast, timeless authority",
    previewColors: ["#080808", "#ffffff", "#d4d4d8", "#181818"],
    accentColor: "#ffffff",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#080808",
          shapesColor: "#ffffff",
        },
        headingColor: "#ffffff",
        bioTextColor: "#a1a1aa",
      },
      linkStyle: {
        surfaceColor: "#141414",
        borderColor: "rgba(255, 255, 255, 0.25)",
        textColor: "#ffffff",
        subtextColor: "#a1a1aa",
        iconColor: "#ffffff",
        glowColor: "#ffffff",
        glowEnabled: false,
        glowOpacity: 20,
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 10. RETRO & NOSTALGIA
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: "gameboy-olive",
    name: "1989 GameBoy 8-Bit Olive",
    category: "Retro",
    description: "Authentic original dot-matrix olive green LCD screen nostalgia",
    previewColors: ["#1b2612", "#9bbc0f", "#8bac0f", "#306230"],
    accentColor: "#9bbc0f",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#1b2612",
          shapesColor: "#9bbc0f",
        },
        headingColor: "#9bbc0f",
        bioTextColor: "#8bac0f",
      },
      linkStyle: {
        surfaceColor: "#233318",
        borderColor: "rgba(155, 188, 15, 0.4)",
        textColor: "#9bbc0f",
        subtextColor: "#8bac0f",
        iconColor: "#9bbc0f",
        glowColor: "#9bbc0f",
        glowEnabled: true,
        glowOpacity: 55,
      },
    },
  },
  {
    id: "crt-amber",
    name: "Amber Phosphor CRT",
    category: "Retro",
    description: "1980s glowing amber mainframe monitor with retro glow bloom",
    previewColors: ["#0d0800", "#ffb000", "#ffd066", "#1f1300"],
    accentColor: "#ffb000",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#0d0800",
          shapesColor: "#ffb000",
        },
        headingColor: "#ffd066",
        bioTextColor: "#ffb000",
      },
      linkStyle: {
        surfaceColor: "#1a1000",
        borderColor: "rgba(255, 176, 0, 0.4)",
        textColor: "#fff4cc",
        subtextColor: "#ffb000",
        iconColor: "#ffb000",
        glowColor: "#ffb000",
        glowEnabled: true,
        glowOpacity: 70,
      },
    },
  },
  {
    id: "vintage-polaroid",
    name: "Vintage Polaroid Film",
    category: "Retro",
    description: "Classic instant camera palette: warm sepia, spectrum rainbow, and analog film",
    previewColors: ["#1a1512", "#ea580c", "#3b82f6", "#2c231f"],
    accentColor: "#ea580c",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#1a1512",
          shapesColor: "#ea580c",
        },
        headingColor: "#fafaf9",
        bioTextColor: "#38bdf8",
      },
      linkStyle: {
        surfaceColor: "#27201c",
        borderColor: "rgba(234, 88, 12, 0.35)",
        textColor: "#f5f5f4",
        subtextColor: "#fb923c",
        iconColor: "#3b82f6",
        glowColor: "#ea580c",
        glowEnabled: true,
        glowOpacity: 55,
      },
    },
  },
  {
    id: "vinyl-jazz-club",
    name: "Blue Note Jazz & Vinyl",
    category: "Retro",
    description: "Late-night smoky jazz lounge with warm brass horn gold and vinyl black",
    previewColors: ["#120c0b", "#d97706", "#fde68a", "#241816"],
    accentColor: "#d97706",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#120c0b",
          gradientAngle: 145,
          gradientStops: [
            { color: "#120c0b", position: 0 },
            { color: "#1f1412", position: 50 },
            { color: "#2d1a16", position: 100 },
          ],
          shapesColor: "#d97706",
        },
        headingColor: "#fef3c7",
        bioTextColor: "#fed7aa",
      },
      linkStyle: {
        surfaceColor: "#221614",
        borderColor: "rgba(217, 119, 6, 0.35)",
        textColor: "#ffffff",
        subtextColor: "#fde68a",
        iconColor: "#d97706",
        glowColor: "#d97706",
        glowEnabled: true,
        glowOpacity: 55,
      },
    },
  },
];
