import { BioConfig } from "@/types/config";

export const DEFAULT_CONFIG: BioConfig = {
  identity: {
    avatarUrl: "",
    displayName: "Your Name",
    subtitle: "Developer · Creator · Dreamer ✨",
    verified: true,
    socialLinks: [
      { id: "s1", platform: "github", url: "https://github.com" },
      { id: "s2", platform: "twitter", url: "https://x.com" },
      { id: "s3", platform: "linkedin", url: "https://linkedin.com" },
      { id: "s4", platform: "instagram", url: "https://instagram.com" },
      { id: "s5", platform: "email", url: "mailto:hello@example.com" },
    ],
    socialLayoutStyle: "minimal",
  },
  theme: {
    background: {
      type: "linear-gradient",
      solidColor: "#0f0f23",
      gradientAngle: 135,
      gradientStops: [
        { color: "#0f0f23", position: 0 },
        { color: "#1a1a3e", position: 50 },
        { color: "#2d1b69", position: 100 },
      ],
      meshColors: ["#667eea", "#764ba2", "#f093fb", "#5ee7df"],
    },
    fontFamily: "sans",
    fontScale: 1,
    headingColor: "#ffffff",
    bioTextColor: "#a0a0c0",
  },
  linkStyle: {
    cornerRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    surfaceTreatment: "glass",
    surfaceColor: "#ffffff",
    surfaceOpacity: 8,
    hoverEffect: "lift",
    textColor: "#ffffff",
    subtextColor: "#9ca3af",
    iconColor: "#a78bfa",
  },
  links: [
    {
      id: "l1",
      title: "My Portfolio",
      url: "https://example.com",
      subtitle: "Check out my latest work",
      icon: "Globe",
      badge: "Featured",
      badgeColor: "#a78bfa",
      clicks: 1247,
      enabled: true,
    },
    {
      id: "l2",
      title: "Latest Blog Post",
      url: "https://blog.example.com",
      subtitle: "Building with Next.js & AI",
      icon: "FileText",
      badge: "New",
      badgeColor: "#34d399",
      clicks: 832,
      enabled: true,
    },
    {
      id: "l3",
      title: "YouTube Channel",
      url: "https://youtube.com",
      subtitle: "Weekly dev tutorials",
      icon: "Play",
      badge: "",
      badgeColor: "#f87171",
      clicks: 2451,
      enabled: true,
    },
    {
      id: "l4",
      title: "Open Source Projects",
      url: "https://github.com",
      subtitle: "Explore my repositories",
      icon: "Code2",
      badge: "",
      badgeColor: "#60a5fa",
      clicks: 619,
      enabled: true,
    },
    {
      id: "l5",
      title: "Book a Call",
      url: "https://cal.com",
      subtitle: "Let's chat about your project",
      icon: "Calendar",
      badge: "Must See",
      badgeColor: "#fbbf24",
      clicks: 384,
      enabled: true,
    },
  ],
  analytics: {
    showClickCounts: true,
  },
};
