import { BioConfig } from "@/types/config";

export const BACKGROUND_PRESETS = [
  {
    id: "glass-glow",
    name: "Liquid Prism",
    url: "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "dark-abstract",
    name: "Dark Waves",
    url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "neon-cyber",
    name: "Neon Lights",
    url: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "deep-space",
    name: "Deep Space",
    url: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "sunset-dusk",
    name: "Sunset Glow",
    url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "minimal-gradient",
    name: "Silk Lavender",
    url: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=1200&q=80",
  },
];

export const DEFAULT_CONFIG: BioConfig = {
  identity: {
    avatarUrl: "",
    displayName: "Your Name",
    subtitle: "Developer · Creator · Dreamer ✨",
    verified: true,
    socialLinks: [
      { id: "s1", platform: "github", url: "https://github.com" },
      { id: "s2", platform: "twitter", url: "https://x.com" },
      { id: "s3", platform: "linkedin", url: "https://linkedin.com" },
      { id: "s4", platform: "instagram", url: "https://instagram.com" },
      { id: "s5", platform: "email", url: "mailto:hello@example.com" },
    ],
    socialLayoutStyle: "minimal",
    avatarShape: "circle",
    avatarSize: 96,
    avatarBorderWidth: 2,
    avatarBorderColor: "rgba(255,255,255,0.25)",
    avatarBorderStyle: "solid",
    avatarGlow: true,
    avatarGlowColor: "#8b5cf6",
    avatarGlowRadius: 18,
    avatarGlowPulse: false,
  },
  theme: {
    background: {
      type: "linear-gradient",
      solidColor: "#0f0f23",
      gradientAngle: 135,
      gradientStops: [
        { color: "#0f0f23", position: 0 },
        { color: "#1a1a3e", position: 50 },
        { color: "#2d1b69", position: 100 },
      ],
      meshColors: ["#667eea", "#764ba2", "#f093fb", "#5ee7df"],
      imageUrl: "",
      imageOpacity: 85,
      imageBlur: 0,
      imageOverlayColor: "#000000",
      imageOverlayOpacity: 35,
      imageFit: "cover",
      imagePosition: "center",
      shapesEnabled: true,
      shapesStyle: "blobs",
      shapesOpacity: 30,
      shapesColor: "#8b5cf6",
      shapesSpeed: "normal",
    },
    fontFamily: "sans",
    fontScale: 1,
    headingColor: "#ffffff",
    bioTextColor: "#a0a0c0",
  },
  linkStyle: {
    cornerRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    surfaceTreatment: "liquid-glass",
    surfaceColor: "#ffffff",
    surfaceOpacity: 12,
    hoverEffect: "lift",
    textColor: "#ffffff",
    subtextColor: "#9ca3af",
    iconColor: "#a78bfa",
    shadow: "subtle",
    liquidGlassGleam: true,
    badgeStyle: "pill",
  },
  links: [
    {
      id: "l1",
      title: "My Portfolio",
      url: "https://example.com",
      subtitle: "Check out my latest work",
      icon: "Globe",
      badge: "Featured",
      badgeColor: "#ffffff",
      badgeBgColor: "#8b5cf6",
      clicks: 1247,
      enabled: true,
    },
    {
      id: "l2",
      title: "Latest Blog Post",
      url: "https://blog.example.com",
      subtitle: "Building with Next.js & AI",
      icon: "FileText",
      badge: "New",
      badgeColor: "#064e3b",
      badgeBgColor: "#34d399",
      clicks: 832,
      enabled: true,
    },
    {
      id: "l3",
      title: "YouTube Channel",
      url: "https://youtube.com",
      subtitle: "Weekly dev tutorials",
      icon: "Play",
      badge: "",
      badgeColor: "#ffffff",
      badgeBgColor: "#f87171",
      clicks: 2451,
      enabled: true,
    },
    {
      id: "l4",
      title: "Open Source Projects",
      url: "https://github.com",
      subtitle: "Explore my repositories",
      icon: "Code2",
      badge: "",
      badgeColor: "#ffffff",
      badgeBgColor: "#60a5fa",
      clicks: 619,
      enabled: true,
    },
    {
      id: "l5",
      title: "Book a Call",
      url: "https://cal.com",
      subtitle: "Let's chat about your project",
      icon: "Calendar",
      badge: "Must See",
      badgeColor: "#78350f",
      badgeBgColor: "#fbbf24",
      clicks: 384,
      enabled: true,
    },
  ],
  analytics: {
    showClickCounts: true,
  },
  footer: {
    enabled: true,
    text: "Thanks for stopping by! Connect with me across platforms ✨",
    subtext: "Designed with passion & LinkTree Studio",
    textColor: "#9ca3af",
    fontSize: 0.85,
    alignment: "center",
    spaceBottom: 32,
    showPoweredBy: true,
  },
};
