import { TemplateConfig } from "@/types/config";

export const TEMPLATES: TemplateConfig[] = [
  {
    id: "apple-liquid-glass",
    name: "Apple Liquid Glass",
    description: "Authentic iOS 18 glassmorphism with specular refraction and aura squircle",
    category: "Modern",
    accentColor: "#a855f7",
    previewGradient: "linear-gradient(135deg, #3b0764, #1e1b4b, #0f172a)",
    badge: "Popular ",
    config: {
      theme: {
        background: {
          type: "image",
          solidColor: "#0f0f23",
          gradientAngle: 135,
          gradientStops: [
            { color: "#0f0f23", position: 0 },
            { color: "#1a1a3e", position: 50 },
            { color: "#2d1b69", position: 100 },
          ],
          meshColors: ["#667eea", "#764ba2", "#f093fb", "#5ee7df"],
          imageUrl:
            "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=1200&q=80",
          imageOpacity: 90,
          imageBlur: 0,
          imageOverlayColor: "#050510",
          imageOverlayOpacity: 25,
          imageFit: "cover",
          imagePosition: "center",
          shapesEnabled: true,
          shapesStyle: "blobs",
          shapesOpacity: 35,
          shapesColor: "#a855f7",
          shapesSpeed: "normal",
        },
        fontFamily: "display",
        fontScale: 1,
        headingColor: "#ffffff",
        bioTextColor: "#cbd5e1",
      },
      identity: {
        avatarShape: "rounded-square",
        avatarSize: 96,
        avatarBorderWidth: 2,
        avatarBorderColor: "rgba(255,255,255,0.4)",
        avatarBorderStyle: "solid",
        avatarGlow: true,
        avatarGlowColor: "#c084fc",
        avatarGlowRadius: 22,
        avatarGlowPulse: true,
        socialLayoutStyle: "minimal",
      },
      linkStyle: {
        cornerRadius: 20,
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.28)",
        surfaceTreatment: "liquid-glass",
        surfaceColor: "#ffffff",
        surfaceOpacity: 12,
        shadow: "elevated",
        liquidGlassGleam: true,
        hoverEffect: "lift",
        textColor: "#ffffff",
        subtextColor: "#94a3b8",
        iconColor: "#c084fc",
        badgeStyle: "pill",
      },
      footer: {
        enabled: true,
        text: "Designed with iPhone Liquid Glass aesthetic ✨",
        subtext: "Connect across all platforms",
        textColor: "#94a3b8",
        fontSize: 0.85,
        alignment: "center",
        spaceBottom: 36,
        showPoweredBy: true,
      },
    },
  },
  {
    id: "cyberpunk-neon",
    name: "Cyberpunk 2077",
    description: "High-tech terminal dark mode with cyan & neon accents and dot matrix grid",
    category: "Dark/Cyber",
    accentColor: "#06b6d4",
    previewGradient: "linear-gradient(135deg, #083344, #020617, #164e63)",
    badge: "Trending ⚡",
    config: {
      theme: {
        background: {
          type: "image",
          solidColor: "#050711",
          gradientAngle: 180,
          gradientStops: [
            { color: "#050711", position: 0 },
            { color: "#081b29", position: 100 },
          ],
          meshColors: ["#06b6d4", "#3b82f6", "#ec4899", "#8b5cf6"],
          imageUrl:
            "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=1200&q=80",
          imageOpacity: 85,
          imageBlur: 0,
          imageOverlayColor: "#090919",
          imageOverlayOpacity: 45,
          imageFit: "cover",
          imagePosition: "center",
          shapesEnabled: true,
          shapesStyle: "grid",
          shapesOpacity: 45,
          shapesColor: "#06b6d4",
          shapesSpeed: "normal",
        },
        fontFamily: "mono",
        fontScale: 1,
        headingColor: "#22d3ee",
        bioTextColor: "#94a3b8",
      },
      identity: {
        avatarShape: "hexagon",
        avatarSize: 100,
        avatarBorderWidth: 2,
        avatarBorderColor: "#06b6d4",
        avatarBorderStyle: "solid",
        avatarGlow: true,
        avatarGlowColor: "#06b6d4",
        avatarGlowRadius: 24,
        avatarGlowPulse: true,
        socialLayoutStyle: "floating",
      },
      linkStyle: {
        cornerRadius: 8,
        borderWidth: 1,
        borderColor: "rgba(6,182,212,0.4)",
        surfaceTreatment: "glass",
        surfaceColor: "#0f172a",
        surfaceOpacity: 30,
        shadow: "glow",
        hoverEffect: "glow",
        textColor: "#f8fafc",
        subtextColor: "#64748b",
        iconColor: "#22d3ee",
        badgeStyle: "glow",
      },
      footer: {
        enabled: true,
        text: "TERMINAL_NODE // ONLINE & READY",
        subtext: "Encrypted Transmission 2026",
        textColor: "#06b6d4",
        fontSize: 0.8,
        alignment: "center",
        spaceBottom: 32,
        showPoweredBy: true,
      },
    },
  },
  {
    id: "midnight-nebula",
    name: "Midnight Nebula",
    description: "Deep cosmos space dust with classical typography and twinkling stars",
    category: "Aesthetic",
    accentColor: "#818cf8",
    previewGradient: "linear-gradient(135deg, #1e1b4b, #030712, #312e81)",
    badge: "Cosmic ✨",
    config: {
      theme: {
        background: {
          type: "image",
          solidColor: "#030014",
          gradientAngle: 135,
          gradientStops: [
            { color: "#030014", position: 0 },
            { color: "#0d0b28", position: 50 },
            { color: "#180e3f", position: 100 },
          ],
          meshColors: ["#6366f1", "#a855f7", "#3b82f6", "#ec4899"],
          imageUrl:
            "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80",
          imageOpacity: 90,
          imageBlur: 0,
          imageOverlayColor: "#030014",
          imageOverlayOpacity: 30,
          imageFit: "cover",
          imagePosition: "center",
          shapesEnabled: true,
          shapesStyle: "stars",
          shapesOpacity: 50,
          shapesColor: "#ffffff",
          shapesSpeed: "normal",
        },
        fontFamily: "cinzel",
        fontScale: 1.05,
        headingColor: "#f1f5f9",
        bioTextColor: "#cbd5e1",
      },
      identity: {
        avatarShape: "circle",
        avatarSize: 96,
        avatarBorderWidth: 2,
        avatarBorderColor: "rgba(255,255,255,0.3)",
        avatarBorderStyle: "solid",
        avatarGlow: true,
        avatarGlowColor: "#818cf8",
        avatarGlowRadius: 20,
        avatarGlowPulse: false,
        socialLayoutStyle: "minimal",
      },
      linkStyle: {
        cornerRadius: 18,
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.18)",
        surfaceTreatment: "liquid-glass",
        surfaceColor: "#1e1b4b",
        surfaceOpacity: 16,
        shadow: "elevated",
        liquidGlassGleam: true,
        hoverEffect: "scale",
        textColor: "#ffffff",
        subtextColor: "#94a3b8",
        iconColor: "#a5b4fc",
        badgeStyle: "pill",
      },
      footer: {
        enabled: true,
        text: "“Somewhere, something incredible is waiting to be known.”",
        subtext: "Voyager Profile",
        textColor: "#94a3b8",
        fontSize: 0.85,
        alignment: "center",
        spaceBottom: 36,
        showPoweredBy: true,
      },
    },
  },
  {
    id: "golden-hour",
    name: "Golden Hour Sunset",
    description: "Warm amber dusk glow with avant-garde fonts and soft bokeh lights",
    category: "Vibrant",
    accentColor: "#f59e0b",
    previewGradient: "linear-gradient(135deg, #78350f, #451a03, #b45309)",
    badge: "Warm 🌅",
    config: {
      theme: {
        background: {
          type: "image",
          solidColor: "#180c04",
          gradientAngle: 135,
          gradientStops: [
            { color: "#180c04", position: 0 },
            { color: "#2e1203", position: 50 },
            { color: "#451a03", position: 100 },
          ],
          meshColors: ["#f59e0b", "#d97706", "#b45309", "#92400e"],
          imageUrl:
            "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
          imageOpacity: 85,
          imageBlur: 0,
          imageOverlayColor: "#1f1005",
          imageOverlayOpacity: 40,
          imageFit: "cover",
          imagePosition: "center",
          shapesEnabled: true,
          shapesStyle: "bokeh",
          shapesOpacity: 35,
          shapesColor: "#f59e0b",
          shapesSpeed: "normal",
        },
        fontFamily: "syne",
        fontScale: 1,
        headingColor: "#fef3c7",
        bioTextColor: "#fed7aa",
      },
      identity: {
        avatarShape: "circle",
        avatarSize: 96,
        avatarBorderWidth: 2,
        avatarBorderColor: "#f59e0b",
        avatarBorderStyle: "solid",
        avatarGlow: true,
        avatarGlowColor: "#f59e0b",
        avatarGlowRadius: 25,
        avatarGlowPulse: false,
        socialLayoutStyle: "pill",
      },
      linkStyle: {
        cornerRadius: 16,
        borderWidth: 1,
        borderColor: "rgba(245,158,11,0.3)",
        surfaceTreatment: "liquid-glass",
        surfaceColor: "#291500",
        surfaceOpacity: 15,
        shadow: "subtle",
        liquidGlassGleam: true,
        hoverEffect: "lift",
        textColor: "#fffbeb",
        subtextColor: "#fde68a",
        iconColor: "#fbbf24",
        badgeStyle: "solid",
      },
      footer: {
        enabled: true,
        text: "Catching sunbeams & chasing big ideas ☀️",
        subtext: "Based in California • Available Worldwide",
        textColor: "#fed7aa",
        fontSize: 0.85,
        alignment: "center",
        spaceBottom: 32,
        showPoweredBy: true,
      },
    },
  },
  {
    id: "matcha-zen",
    name: "Matcha Botanical Zen",
    description: "Serene emerald forest palette with clean rounded shapes and organic calm",
    category: "Nature",
    accentColor: "#10b981",
    previewGradient: "linear-gradient(135deg, #064e3b, #022c22, #065f46)",
    badge: "Organic 🍃",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#041b14",
          gradientAngle: 160,
          gradientStops: [
            { color: "#03140e", position: 0 },
            { color: "#062b1e", position: 50 },
            { color: "#0a3d2c", position: 100 },
          ],
          meshColors: ["#059669", "#10b981", "#34d399", "#6ee7b7"],
          imageUrl: "",
          imageOpacity: 85,
          imageBlur: 0,
          imageOverlayColor: "#000000",
          imageOverlayOpacity: 30,
          imageFit: "cover",
          imagePosition: "center",
          shapesEnabled: true,
          shapesStyle: "blobs",
          shapesOpacity: 25,
          shapesColor: "#10b981",
          shapesSpeed: "slow",
        },
        fontFamily: "rounded",
        fontScale: 1,
        headingColor: "#ecfdf5",
        bioTextColor: "#a7f3d0",
      },
      identity: {
        avatarShape: "rounded-square",
        avatarSize: 96,
        avatarBorderWidth: 2,
        avatarBorderColor: "rgba(52,211,153,0.3)",
        avatarBorderStyle: "solid",
        avatarGlow: true,
        avatarGlowColor: "#34d399",
        avatarGlowRadius: 20,
        avatarGlowPulse: false,
        socialLayoutStyle: "pill",
      },
      linkStyle: {
        cornerRadius: 18,
        borderWidth: 1,
        borderColor: "rgba(52,211,153,0.2)",
        surfaceTreatment: "liquid-glass",
        surfaceColor: "#064e3b",
        surfaceOpacity: 20,
        shadow: "subtle",
        liquidGlassGleam: true,
        hoverEffect: "lift",
        textColor: "#ecfdf5",
        subtextColor: "#6ee7b7",
        iconColor: "#34d399",
        badgeStyle: "pill",
      },
      footer: {
        enabled: true,
        text: "Cultivating calmness, creativity, and conscious craft 🍵",
        subtext: "Peaceful Living & Clean Code",
        textColor: "#a7f3d0",
        fontSize: 0.85,
        alignment: "center",
        spaceBottom: 36,
        showPoweredBy: true,
      },
    },
  },
  {
    id: "swiss-brutalist",
    name: "Swiss Brutalism",
    description: "High-contrast monochrome with stark typography and geometric structure",
    category: "Minimal",
    accentColor: "#ffffff",
    previewGradient: "linear-gradient(135deg, #18181b, #09090b, #27272a)",
    badge: "Minimal 🖤",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#09090b",
          gradientAngle: 0,
          gradientStops: [
            { color: "#09090b", position: 0 },
            { color: "#18181b", position: 100 },
          ],
          meshColors: ["#27272a", "#3f3f46", "#52525b", "#71717a"],
          imageUrl: "",
          imageOpacity: 85,
          imageBlur: 0,
          imageOverlayColor: "#000000",
          imageOverlayOpacity: 30,
          imageFit: "cover",
          imagePosition: "center",
          shapesEnabled: true,
          shapesStyle: "geometric",
          shapesOpacity: 20,
          shapesColor: "#ffffff",
          shapesSpeed: "normal",
        },
        fontFamily: "bricolage",
        fontScale: 1.05,
        headingColor: "#ffffff",
        bioTextColor: "#a1a1aa",
      },
      identity: {
        avatarShape: "square",
        avatarSize: 90,
        avatarBorderWidth: 2,
        avatarBorderColor: "#ffffff",
        avatarBorderStyle: "solid",
        avatarGlow: false,
        avatarGlowColor: "#ffffff",
        avatarGlowRadius: 0,
        avatarGlowPulse: false,
        socialLayoutStyle: "minimal",
      },
      linkStyle: {
        cornerRadius: 4,
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.2)",
        surfaceTreatment: "solid",
        surfaceColor: "#18181b",
        surfaceOpacity: 100,
        shadow: "none",
        liquidGlassGleam: false,
        hoverEffect: "lift",
        textColor: "#ffffff",
        subtextColor: "#71717a",
        iconColor: "#ffffff",
        badgeStyle: "outline",
      },
      footer: {
        enabled: true,
        text: "FORM FOLLOWS FUNCTION • LESS IS MORE",
        subtext: "Zurich Inspired Design",
        textColor: "#71717a",
        fontSize: 0.8,
        alignment: "center",
        spaceBottom: 32,
        showPoweredBy: true,
      },
    },
  },
  {
    id: "royal-velvet",
    name: "Royal Velvet & Gold",
    description: "Burgundy wine velvet with 18k gold accents, editorial serif, and prestige",
    category: "Luxury",
    accentColor: "#eab308",
    previewGradient: "linear-gradient(135deg, #450a0a, #1a0505, #78350f)",
    badge: "Prestige 👑",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#170308",
          gradientAngle: 145,
          gradientStops: [
            { color: "#170308", position: 0 },
            { color: "#2d0815", position: 50 },
            { color: "#14020b", position: 100 },
          ],
          meshColors: ["#eab308", "#991b1b", "#ca8a04", "#7f1d1d"],
          imageUrl: "",
          imageOpacity: 85,
          imageBlur: 0,
          imageOverlayColor: "#000000",
          imageOverlayOpacity: 30,
          imageFit: "cover",
          imagePosition: "center",
          shapesEnabled: true,
          shapesStyle: "rings",
          shapesOpacity: 35,
          shapesColor: "#eab308",
          shapesSpeed: "slow",
        },
        fontFamily: "serif",
        fontScale: 1.05,
        headingColor: "#fef08a",
        bioTextColor: "#fecdd3",
      },
      identity: {
        avatarShape: "octagon",
        avatarSize: 96,
        avatarBorderWidth: 2,
        avatarBorderColor: "#eab308",
        avatarBorderStyle: "solid",
        avatarGlow: true,
        avatarGlowColor: "#eab308",
        avatarGlowRadius: 22,
        avatarGlowPulse: false,
        socialLayoutStyle: "minimal",
      },
      linkStyle: {
        cornerRadius: 14,
        borderWidth: 1,
        borderColor: "rgba(234,179,8,0.35)",
        surfaceTreatment: "liquid-glass",
        surfaceColor: "#260613",
        surfaceOpacity: 25,
        shadow: "elevated",
        liquidGlassGleam: true,
        hoverEffect: "lift",
        textColor: "#fef9c3",
        subtextColor: "#fca5a5",
        iconColor: "#facc15",
        badgeStyle: "glow",
      },
      footer: {
        enabled: true,
        text: "Excellence is not an act, but a habit.",
        subtext: "Private Collection & Portfolio",
        textColor: "#fca5a5",
        fontSize: 0.85,
        alignment: "center",
        spaceBottom: 36,
        showPoweredBy: true,
      },
    },
  },
  {
    id: "sakura-pastel",
    name: "Sakura Pastel Dream",
    description: "Gentle rose quartz & lavender clouds with rounded pill capsules and soft aura",
    category: "Aesthetic",
    accentColor: "#f472b6",
    previewGradient: "linear-gradient(135deg, #831843, #3b0764, #500724)",
    badge: "Cute 🌸",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#1d081f",
          gradientAngle: 135,
          gradientStops: [
            { color: "#1d081f", position: 0 },
            { color: "#2e0f2f", position: 50 },
            { color: "#160517", position: 100 },
          ],
          meshColors: ["#f472b6", "#c084fc", "#fb7185", "#fbcfe8"],
          imageUrl:
            "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=1200&q=80",
          imageOpacity: 75,
          imageBlur: 8,
          imageOverlayColor: "#15021a",
          imageOverlayOpacity: 45,
          imageFit: "cover",
          imagePosition: "center",
          shapesEnabled: true,
          shapesStyle: "bokeh",
          shapesOpacity: 35,
          shapesColor: "#f472b6",
          shapesSpeed: "normal",
        },
        fontFamily: "poppins",
        fontScale: 1,
        headingColor: "#fce7f3",
        bioTextColor: "#f5d0fe",
      },
      identity: {
        avatarShape: "circle",
        avatarSize: 96,
        avatarBorderWidth: 3,
        avatarBorderColor: "#f472b6",
        avatarBorderStyle: "solid",
        avatarGlow: true,
        avatarGlowColor: "#f472b6",
        avatarGlowRadius: 24,
        avatarGlowPulse: true,
        socialLayoutStyle: "pill",
      },
      linkStyle: {
        cornerRadius: 9999,
        borderWidth: 1,
        borderColor: "rgba(244,114,182,0.3)",
        surfaceTreatment: "liquid-glass",
        surfaceColor: "#330b35",
        surfaceOpacity: 20,
        shadow: "subtle",
        liquidGlassGleam: true,
        hoverEffect: "scale",
        textColor: "#fdf2f8",
        subtextColor: "#f0abfc",
        iconColor: "#f472b6",
        badgeStyle: "pill",
      },
      footer: {
        enabled: true,
        text: "Spreading softness, smiles, and good vibes 🌸",
        subtext: "Tokyo • Kyoto • Worldwide",
        textColor: "#f5d0fe",
        fontSize: 0.85,
        alignment: "center",
        spaceBottom: 32,
        showPoweredBy: true,
      },
    },
  },
  {
    id: "deep-ocean",
    name: "Bioluminescent Abyss",
    description: "Deep ocean navy depths with electric sapphire glow and orbital rings",
    category: "Dark/Cyber",
    accentColor: "#38bdf8",
    previewGradient: "linear-gradient(135deg, #082f49, #020617, #0c4a6e)",
    badge: "Ocean 🌊",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#020b14",
          gradientAngle: 180,
          gradientStops: [
            { color: "#020b14", position: 0 },
            { color: "#051f38", position: 50 },
            { color: "#010912", position: 100 },
          ],
          meshColors: ["#0284c7", "#38bdf8", "#0369a1", "#075985"],
          imageUrl: "",
          imageOpacity: 85,
          imageBlur: 0,
          imageOverlayColor: "#000000",
          imageOverlayOpacity: 30,
          imageFit: "cover",
          imagePosition: "center",
          shapesEnabled: true,
          shapesStyle: "rings",
          shapesOpacity: 40,
          shapesColor: "#38bdf8",
          shapesSpeed: "normal",
        },
        fontFamily: "display",
        fontScale: 1,
        headingColor: "#e0f2fe",
        bioTextColor: "#7dd3fc",
      },
      identity: {
        avatarShape: "hexagon",
        avatarSize: 96,
        avatarBorderWidth: 2,
        avatarBorderColor: "#38bdf8",
        avatarBorderStyle: "solid",
        avatarGlow: true,
        avatarGlowColor: "#38bdf8",
        avatarGlowRadius: 26,
        avatarGlowPulse: true,
        socialLayoutStyle: "floating",
      },
      linkStyle: {
        cornerRadius: 16,
        borderWidth: 1,
        borderColor: "rgba(56,189,248,0.25)",
        surfaceTreatment: "liquid-glass",
        surfaceColor: "#04192b",
        surfaceOpacity: 25,
        shadow: "glow",
        liquidGlassGleam: true,
        hoverEffect: "lift",
        textColor: "#f0f9ff",
        subtextColor: "#38bdf8",
        iconColor: "#7dd3fc",
        badgeStyle: "glow",
      },
      footer: {
        enabled: true,
        text: "Diving deep into the uncharted digital ocean 🐋",
        subtext: "Marine Blue Architecture",
        textColor: "#7dd3fc",
        fontSize: 0.85,
        alignment: "center",
        spaceBottom: 36,
        showPoweredBy: true,
      },
    },
  },
  {
    id: "solar-flare",
    name: "Solar Flare & Magma",
    description: "Fiery orange magma gradient with bold punchy typography and blazing glow",
    category: "Vibrant",
    accentColor: "#ea580c",
    previewGradient: "linear-gradient(135deg, #7c2d12, #1c0a04, #9a3412)",
    badge: "Fiery 🔥",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#140602",
          gradientAngle: 135,
          gradientStops: [
            { color: "#140602", position: 0 },
            { color: "#2d0e04", position: 50 },
            { color: "#451608", position: 100 },
          ],
          meshColors: ["#ea580c", "#f97316", "#c2410c", "#fb923c"],
          imageUrl: "",
          imageOpacity: 85,
          imageBlur: 0,
          imageOverlayColor: "#000000",
          imageOverlayOpacity: 30,
          imageFit: "cover",
          imagePosition: "center",
          shapesEnabled: true,
          shapesStyle: "blobs",
          shapesOpacity: 35,
          shapesColor: "#ea580c",
          shapesSpeed: "fast",
        },
        fontFamily: "bebas",
        fontScale: 1.1,
        headingColor: "#ffedd5",
        bioTextColor: "#fed7aa",
      },
      identity: {
        avatarShape: "rounded-square",
        avatarSize: 98,
        avatarBorderWidth: 2,
        avatarBorderColor: "#ea580c",
        avatarBorderStyle: "solid",
        avatarGlow: true,
        avatarGlowColor: "#ea580c",
        avatarGlowRadius: 28,
        avatarGlowPulse: true,
        socialLayoutStyle: "pill",
      },
      linkStyle: {
        cornerRadius: 12,
        borderWidth: 1,
        borderColor: "rgba(234,88,12,0.4)",
        surfaceTreatment: "solid",
        surfaceColor: "#210903",
        surfaceOpacity: 100,
        shadow: "elevated",
        liquidGlassGleam: false,
        hoverEffect: "scale",
        textColor: "#ffedd5",
        subtextColor: "#fdba74",
        iconColor: "#f97316",
        badgeStyle: "solid",
      },
      footer: {
        enabled: true,
        text: "STAY HUNGRY • FUEL THE FIRE • BREAK LIMITS",
        subtext: "High Performance Creator",
        textColor: "#fed7aa",
        fontSize: 0.85,
        alignment: "center",
        spaceBottom: 32,
        showPoweredBy: true,
      },
    },
  },
  {
    id: "dark-academia",
    name: "Dark Academia Writer",
    description: "Refined sepia charcoal slate with fine hairline outlines and editorial prose",
    category: "Luxury",
    accentColor: "#d4d4d8",
    previewGradient: "linear-gradient(135deg, #27272a, #18181b, #1c1917)",
    badge: "Writer 🖋️",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#121214",
          gradientAngle: 0,
          gradientStops: [
            { color: "#121214", position: 0 },
            { color: "#1c1c20", position: 100 },
          ],
          meshColors: ["#27272a", "#3f3f46", "#52525b", "#71717a"],
          imageUrl: "",
          imageOpacity: 85,
          imageBlur: 0,
          imageOverlayColor: "#000000",
          imageOverlayOpacity: 30,
          imageFit: "cover",
          imagePosition: "center",
          shapesEnabled: true,
          shapesStyle: "geometric",
          shapesOpacity: 15,
          shapesColor: "#a1a1aa",
          shapesSpeed: "slow",
        },
        fontFamily: "serif",
        fontScale: 1,
        headingColor: "#f4f4f5",
        bioTextColor: "#a1a1aa",
      },
      identity: {
        avatarShape: "circle",
        avatarSize: 92,
        avatarBorderWidth: 1,
        avatarBorderColor: "rgba(255,255,255,0.3)",
        avatarBorderStyle: "solid",
        avatarGlow: false,
        avatarGlowColor: "#ffffff",
        avatarGlowRadius: 0,
        avatarGlowPulse: false,
        socialLayoutStyle: "minimal",
      },
      linkStyle: {
        cornerRadius: 12,
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.15)",
        surfaceTreatment: "outline",
        surfaceColor: "#18181b",
        surfaceOpacity: 0,
        shadow: "none",
        liquidGlassGleam: false,
        hoverEffect: "lift",
        textColor: "#fafafa",
        subtextColor: "#71717a",
        iconColor: "#e4e4e7",
        badgeStyle: "outline",
      },
      footer: {
        enabled: true,
        text: "“Words are our most inexhaustible source of magic.”",
        subtext: "Essays, Critiques, & Stories",
        textColor: "#71717a",
        fontSize: 0.85,
        alignment: "center",
        spaceBottom: 36,
        showPoweredBy: true,
      },
    },
  },
  {
    id: "synthwave-80s",
    name: "Retro Synthwave 80s",
    description: "Outrun neon magenta & purple horizon with retro cyber grid and neon pop",
    category: "Dark/Cyber",
    accentColor: "#f43f5e",
    previewGradient: "linear-gradient(135deg, #881337, #2e0854, #be123c)",
    badge: "Retro 👾",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#12021c",
          gradientAngle: 180,
          gradientStops: [
            { color: "#130024", position: 0 },
            { color: "#2d083e", position: 50 },
            { color: "#4a0635", position: 100 },
          ],
          meshColors: ["#f43f5e", "#a855f7", "#ec4899", "#d946ef"],
          imageUrl: "",
          imageOpacity: 85,
          imageBlur: 0,
          imageOverlayColor: "#000000",
          imageOverlayOpacity: 30,
          imageFit: "cover",
          imagePosition: "center",
          shapesEnabled: true,
          shapesStyle: "grid",
          shapesOpacity: 50,
          shapesColor: "#ec4899",
          shapesSpeed: "normal",
        },
        fontFamily: "mono",
        fontScale: 1,
        headingColor: "#fdf2f8",
        bioTextColor: "#f472b6",
      },
      identity: {
        avatarShape: "rounded-square",
        avatarSize: 96,
        avatarBorderWidth: 2,
        avatarBorderColor: "#f43f5e",
        avatarBorderStyle: "solid",
        avatarGlow: true,
        avatarGlowColor: "#f43f5e",
        avatarGlowRadius: 25,
        avatarGlowPulse: true,
        socialLayoutStyle: "floating",
      },
      linkStyle: {
        cornerRadius: 12,
        borderWidth: 1,
        borderColor: "rgba(244,63,94,0.4)",
        surfaceTreatment: "glass",
        surfaceColor: "#290435",
        surfaceOpacity: 35,
        shadow: "glow",
        hoverEffect: "glow",
        textColor: "#fff1f2",
        subtextColor: "#f472b6",
        iconColor: "#fb7185",
        badgeStyle: "glow",
      },
      footer: {
        enabled: true,
        text: "NEON HIGHWAY • 1984 CASSETTE TAPE CULTURE",
        subtext: "Synthwave Beats & Visuals",
        textColor: "#f472b6",
        fontSize: 0.8,
        alignment: "center",
        spaceBottom: 32,
        showPoweredBy: true,
      },
    },
  },
  {
    id: "nordic-frost",
    name: "Nordic Frost & Ice",
    description: "Crisp glacial blue & silver frost with clean modern sans and pure clarity",
    category: "Modern",
    accentColor: "#67e8f9",
    previewGradient: "linear-gradient(135deg, #0e2a47, #071526, #16426f)",
    badge: "Ice 🤍",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#08131e",
          gradientAngle: 150,
          gradientStops: [
            { color: "#08131e", position: 0 },
            { color: "#102336", position: 50 },
            { color: "#193652", position: 100 },
          ],
          meshColors: ["#06b6d4", "#67e8f9", "#0284c7", "#a5f3fc"],
          imageUrl: "",
          imageOpacity: 85,
          imageBlur: 0,
          imageOverlayColor: "#000000",
          imageOverlayOpacity: 30,
          imageFit: "cover",
          imagePosition: "center",
          shapesEnabled: true,
          shapesStyle: "bokeh",
          shapesOpacity: 30,
          shapesColor: "#67e8f9",
          shapesSpeed: "slow",
        },
        fontFamily: "sans",
        fontScale: 1,
        headingColor: "#f0fdfa",
        bioTextColor: "#a5f3fc",
      },
      identity: {
        avatarShape: "circle",
        avatarSize: 96,
        avatarBorderWidth: 2,
        avatarBorderColor: "rgba(103,232,249,0.4)",
        avatarBorderStyle: "solid",
        avatarGlow: true,
        avatarGlowColor: "#67e8f9",
        avatarGlowRadius: 20,
        avatarGlowPulse: false,
        socialLayoutStyle: "minimal",
      },
      linkStyle: {
        cornerRadius: 18,
        borderWidth: 1,
        borderColor: "rgba(103,232,249,0.25)",
        surfaceTreatment: "liquid-glass",
        surfaceColor: "#0a1e30",
        surfaceOpacity: 18,
        shadow: "subtle",
        liquidGlassGleam: true,
        hoverEffect: "lift",
        textColor: "#f0fdfa",
        subtextColor: "#67e8f9",
        iconColor: "#a5f3fc",
        badgeStyle: "pill",
      },
      footer: {
        enabled: true,
        text: "Clean, transparent, and built for simplicity ❄️",
        subtext: "Stockholm • Oslo • Copenhagen",
        textColor: "#a5f3fc",
        fontSize: 0.85,
        alignment: "center",
        spaceBottom: 36,
        showPoweredBy: true,
      },
    },
  },
  {
    id: "creator-studio",
    name: "Handwritten Studio",
    description: "Warm artistic signature vibe with handwritten script font and creator warmth",
    category: "Aesthetic",
    accentColor: "#fbbf24",
    previewGradient: "linear-gradient(135deg, #372a1e, #1c140d, #4d3923)",
    badge: "Artsy 🎨",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#17120e",
          gradientAngle: 135,
          gradientStops: [
            { color: "#17120e", position: 0 },
            { color: "#261d15", position: 50 },
            { color: "#36291e", position: 100 },
          ],
          meshColors: ["#f59e0b", "#d97706", "#b45309", "#78350f"],
          imageUrl: "",
          imageOpacity: 85,
          imageBlur: 0,
          imageOverlayColor: "#000000",
          imageOverlayOpacity: 30,
          imageFit: "cover",
          imagePosition: "center",
          shapesEnabled: true,
          shapesStyle: "blobs",
          shapesOpacity: 25,
          shapesColor: "#fbbf24",
          shapesSpeed: "slow",
        },
        fontFamily: "handwritten",
        fontScale: 1.1,
        headingColor: "#fef3c7",
        bioTextColor: "#fed7aa",
      },
      identity: {
        avatarShape: "rounded-square",
        avatarSize: 96,
        avatarBorderWidth: 2,
        avatarBorderColor: "#fbbf24",
        avatarBorderStyle: "solid",
        avatarGlow: true,
        avatarGlowColor: "#fbbf24",
        avatarGlowRadius: 20,
        avatarGlowPulse: false,
        socialLayoutStyle: "minimal",
      },
      linkStyle: {
        cornerRadius: 16,
        borderWidth: 1,
        borderColor: "rgba(251,191,36,0.25)",
        surfaceTreatment: "liquid-glass",
        surfaceColor: "#2e2116",
        surfaceOpacity: 20,
        shadow: "subtle",
        liquidGlassGleam: true,
        hoverEffect: "lift",
        textColor: "#fffbeb",
        subtextColor: "#fed7aa",
        iconColor: "#fbbf24",
        badgeStyle: "pill",
      },
      footer: {
        enabled: true,
        text: "Made by hand with endless curiosity and cups of coffee ☕",
        subtext: "Personal Studio & Sketches",
        textColor: "#fed7aa",
        fontSize: 0.9,
        alignment: "center",
        spaceBottom: 36,
        showPoweredBy: true,
      },
    },
  },
  {
    id: "emerald-matrix",
    name: "Terminal Phosphor Matrix",
    description: "Classic hacker terminal phosphor green on pitch black with cyber grid",
    category: "Dark/Cyber",
    accentColor: "#22c55e",
    previewGradient: "linear-gradient(135deg, #052e16, #021207, #14532d)",
    badge: "Hacker 💎",
    config: {
      theme: {
        background: {
          type: "solid",
          solidColor: "#040d07",
          gradientAngle: 180,
          gradientStops: [
            { color: "#040d07", position: 0 },
            { color: "#092112", position: 100 },
          ],
          meshColors: ["#22c55e", "#16a34a", "#15803d", "#4ade80"],
          imageUrl: "",
          imageOpacity: 85,
          imageBlur: 0,
          imageOverlayColor: "#000000",
          imageOverlayOpacity: 30,
          imageFit: "cover",
          imagePosition: "center",
          shapesEnabled: true,
          shapesStyle: "grid",
          shapesOpacity: 40,
          shapesColor: "#22c55e",
          shapesSpeed: "normal",
        },
        fontFamily: "mono",
        fontScale: 1,
        headingColor: "#4ade80",
        bioTextColor: "#86efac",
      },
      identity: {
        avatarShape: "hexagon",
        avatarSize: 96,
        avatarBorderWidth: 2,
        avatarBorderColor: "#22c55e",
        avatarBorderStyle: "solid",
        avatarGlow: true,
        avatarGlowColor: "#22c55e",
        avatarGlowRadius: 24,
        avatarGlowPulse: true,
        socialLayoutStyle: "floating",
      },
      linkStyle: {
        cornerRadius: 6,
        borderWidth: 1,
        borderColor: "rgba(34,197,94,0.4)",
        surfaceTreatment: "glass",
        surfaceColor: "#071c10",
        surfaceOpacity: 30,
        shadow: "glow",
        hoverEffect: "glow",
        textColor: "#dcfce7",
        subtextColor: "#86efac",
        iconColor: "#4ade80",
        badgeStyle: "glow",
      },
      footer: {
        enabled: true,
        text: "ROOT_ACCESS_GRANTED // PORT 443 OPEN",
        subtext: "Green Phosphor Shell",
        textColor: "#4ade80",
        fontSize: 0.8,
        alignment: "center",
        spaceBottom: 32,
        showPoweredBy: true,
      },
    },
  },
  {
    id: "cotton-candy",
    name: "Cotton Candy Clouds",
    description: "Dreamy lavender & sky blue sunset clouds with translucent glass and gentle glow",
    category: "Aesthetic",
    accentColor: "#a78bfa",
    previewGradient: "linear-gradient(135deg, #4c1d95, #1e1b4b, #2563eb)",
    badge: "Dreamy ☁️",
    config: {
      theme: {
        background: {
          type: "linear-gradient",
          solidColor: "#110e2e",
          gradientAngle: 135,
          gradientStops: [
            { color: "#110e2e", position: 0 },
            { color: "#1f1847", position: 50 },
            { color: "#2c1c5e", position: 100 },
          ],
          meshColors: ["#a78bfa", "#60a5fa", "#f472b6", "#818cf8"],
          imageUrl:
            "https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=1200&q=80",
          imageOpacity: 80,
          imageBlur: 4,
          imageOverlayColor: "#0c0824",
          imageOverlayOpacity: 35,
          imageFit: "cover",
          imagePosition: "center",
          shapesEnabled: true,
          shapesStyle: "bokeh",
          shapesOpacity: 30,
          shapesColor: "#a78bfa",
          shapesSpeed: "slow",
        },
        fontFamily: "rounded",
        fontScale: 1,
        headingColor: "#ede9fe",
        bioTextColor: "#c4b5fd",
      },
      identity: {
        avatarShape: "circle",
        avatarSize: 96,
        avatarBorderWidth: 2,
        avatarBorderColor: "rgba(167,139,250,0.4)",
        avatarBorderStyle: "solid",
        avatarGlow: true,
        avatarGlowColor: "#a78bfa",
        avatarGlowRadius: 22,
        avatarGlowPulse: false,
        socialLayoutStyle: "pill",
      },
      linkStyle: {
        cornerRadius: 20,
        borderWidth: 1,
        borderColor: "rgba(167,139,250,0.25)",
        surfaceTreatment: "liquid-glass",
        surfaceColor: "#251a4a",
        surfaceOpacity: 18,
        shadow: "elevated",
        liquidGlassGleam: true,
        hoverEffect: "scale",
        textColor: "#f5f3ff",
        subtextColor: "#c4b5fd",
        iconColor: "#a78bfa",
        badgeStyle: "pill",
      },
      footer: {
        enabled: true,
        text: "Floating on digital clouds and making things pretty ✨",
        subtext: "Sky High Dreams",
        textColor: "#c4b5fd",
        fontSize: 0.85,
        alignment: "center",
        spaceBottom: 36,
        showPoweredBy: true,
      },
    },
  },
];
